$blogDir = 'c:\Users\HOLA\OneDrive\Escritorio\juristam-web\blog'
$utf8noBOM = New-Object System.Text.UTF8Encoding $false
$updated = 0; $skipped = 0; $notFound = 0

function Find-ArrayClose($str, $startPos) {
    $openPos = $str.IndexOf('[', $startPos)
    if ($openPos -lt 0) { return -1 }
    $depth = 0; $inStr = $false; $esc = $false
    $bsc = [int][char]92; $dqc = [int][char]34
    for ($i = $openPos; $i -lt $str.Length; $i++) {
        $ci = [int][char]$str[$i]
        if ($esc) { $esc = $false; continue }
        if ($ci -eq $bsc -and $inStr) { $esc = $true; continue }
        if ($ci -eq $dqc) { $inStr = !$inStr; continue }
        if (-not $inStr) {
            if ($str[$i] -eq '[') { $depth++ }
            elseif ($str[$i] -eq ']') { $depth--; if ($depth -eq 0) { return $i } }
        }
    }
    return -1
}

function Add-FaqData($filename, $jsonAdd, $htmlAdd) {
    $path = Join-Path $blogDir $filename
    if (-not (Test-Path $path)) { $script:notFound++; Write-Host "NOT FOUND: $filename"; return }
    $c = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
    $marker = $jsonAdd.Substring(0,[Math]::Min(50,$jsonAdd.Length))
    if ($c.IndexOf($marker) -ge 0) { $script:skipped++; Write-Host "SKIP: $filename"; return }
    $tag = '<script type="application/ld+json">'
    $si = $c.IndexOf($tag); $ei = $c.IndexOf('</script>', $si)
    if ($si -ge 0) {
        $jb = $c.Substring($si+$tag.Length, $ei-$si-$tag.Length)
        $fp = $jb.IndexOf('"FAQPage"')
        if ($fp -ge 0) {
            $mp = $jb.IndexOf('"mainEntity"', $fp)
            $cl = Find-ArrayClose $jb $mp
            if ($cl -ge 0) {
                $abs = $si+$tag.Length+$cl
                $c = $c.Substring(0,$abs) + ',' + $jsonAdd + $c.Substring($abs)
            }
        }
    }
    $ld = $c.LastIndexOf('</details>')
    if ($ld -ge 0) {
        $cd = $c.IndexOf('</div>', $ld+10)
        if ($cd -ge 0) { $c = $c.Substring(0,$cd) + $htmlAdd + "`n" + $c.Substring($cd) }
    }
    [System.IO.File]::WriteAllText($path, $c, $utf8noBOM)
    $script:updated++; Write-Host "OK: $filename"
}

Add-FaqData 'testigos-posesion-terreno-requisitos-ecuador.html' `
'{"@type":"Question","name":"¿Puedo usar como testigo a alguien que también posee un terreno sin escritura?","acceptedAnswer":{"@type":"Answer","text":"Sí, no hay incompatibilidad legal. Lo que evalúa el juez es el conocimiento directo del testigo sobre tu posesión. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuánto tiempo antes del juicio debo identificar a mis testigos?","acceptedAnswer":{"@type":"Answer","text":"Lo antes posible, idealmente al inicio del proceso. El abogado los prepara para la declaración y verifica que su testimonio sea consistente y útil. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El testigo puede negarse a declarar en juicio?","acceptedAnswer":{"@type":"Answer","text":"Si fue citado judicialmente, no puede negarse sin justificación. El juez puede ordenar su comparecencia forzosa. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Un testigo que tiene pleitos con el propietario es válido?","acceptedAnswer":{"@type":"Answer","text":"Técnicamente sí, pero el propietario puede tacharlo por parcialidad. El juez evalúa la credibilidad considerando sus posibles intereses. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo usar como testigo a alguien que también posee un terreno sin escritura?</summary><p class="faq-answer">Sí, no hay incompatibilidad legal. Lo que evalúa el juez es el conocimiento directo del testigo sobre tu posesión. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuánto tiempo antes del juicio debo identificar a mis testigos?</summary><p class="faq-answer">Lo antes posible, idealmente al inicio del proceso. El abogado los prepara para la declaración y verifica que su testimonio sea consistente y útil. Escríbenos: 0994859814.</p></details>
<details><summary>¿El testigo puede negarse a declarar en juicio?</summary><p class="faq-answer">Si fue citado judicialmente, no puede negarse sin justificación. El juez puede ordenar su comparecencia forzosa. Escríbenos: 0994859814.</p></details>
<details><summary>¿Un testigo que tiene pleitos con el propietario es válido?</summary><p class="faq-answer">Técnicamente sí, pero el propietario puede tacharlo por parcialidad. El juez evalúa la credibilidad considerando sus posibles intereses. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'vecinos-testigos-posesion-terreno-ecuador.html' `
'{"@type":"Question","name":"¿Cuántos vecinos necesito como testigos?","acceptedAnswer":{"@type":"Answer","text":"No hay un número mínimo legal. Normalmente se presentan entre 2 y 3. Lo que importa es que conozcan directamente tu posesión y puedan declararlo con firmeza. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Sirve como testigo un vecino que llegó después que yo?","acceptedAnswer":{"@type":"Answer","text":"Sí, puede declarar sobre el tiempo que te conoce en el terreno. Para los años anteriores a su llegada, necesitas otros vecinos con más antigüedad. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué preguntas le hace el juez a mis testigos?","acceptedAnswer":{"@type":"Answer","text":"Cuánto tiempo te conocen, cómo saben que posees el terreno, si han visto al propietario reclamar y qué actos has realizado como propietario. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El vecino puede negarse a ser testigo si le da miedo el propietario?","acceptedAnswer":{"@type":"Answer","text":"Si es citado judicialmente tiene obligación de comparecer y declarar con verdad. Escríbenos: 0994859814."}}' `
'<details><summary>¿Cuántos vecinos necesito como testigos?</summary><p class="faq-answer">No hay un número mínimo legal. Normalmente se presentan entre 2 y 3. Lo que importa es que conozcan directamente tu posesión y puedan declararlo con firmeza. Escríbenos: 0994859814.</p></details>
<details><summary>¿Sirve como testigo un vecino que llegó después que yo?</summary><p class="faq-answer">Sí, puede declarar sobre el tiempo que te conoce en el terreno. Para los años anteriores a su llegada, necesitas otros vecinos con más antigüedad. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué preguntas le hace el juez a mis testigos?</summary><p class="faq-answer">Cuánto tiempo te conocen, cómo saben que posees el terreno, si han visto al propietario reclamar y qué actos has realizado como propietario. Escríbenos: 0994859814.</p></details>
<details><summary>¿El vecino puede negarse a ser testigo si le da miedo el propietario?</summary><p class="faq-answer">Si es citado judicialmente tiene obligación de comparecer y declarar con verdad. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'plazo-5-vs-15-anos-prescripcion-ecuador.html' `
'{"@type":"Question","name":"¿Siempre es mejor la ordinaria por ser más rápida?","acceptedAnswer":{"@type":"Answer","text":"No. Si no tienes un justo título claro, forzar la ordinaria puede generar más debate que ir directamente por la extraordinaria de 15 años. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Los 5 años de la ordinaria empiezan desde cuándo exactamente?","acceptedAnswer":{"@type":"Answer","text":"Desde que adquiriste la posesión con justo título y buena fe. No desde la firma del contrato sino desde que tomaste posesión real del inmueble. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La prescripción extraordinaria aplica para terrenos urbanos también?","acceptedAnswer":{"@type":"Answer","text":"Sí. Aplica tanto para terrenos urbanos como rurales. Los requisitos son los mismos en ambos casos. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo cambiar de la ordinaria a la extraordinaria si me rechazan la primera?","acceptedAnswer":{"@type":"Answer","text":"Puedes intentarlo con la extraordinaria si cumples los 15 años. Pero perderás el tiempo invertido en el primer juicio. Escríbenos: 0994859814."}}' `
'<details><summary>¿Siempre es mejor la ordinaria por ser más rápida?</summary><p class="faq-answer">No. Si no tienes un justo título claro, forzar la ordinaria puede generar más debate que ir directamente por la extraordinaria de 15 años. Escríbenos: 0994859814.</p></details>
<details><summary>¿Los 5 años de la ordinaria empiezan desde cuándo exactamente?</summary><p class="faq-answer">Desde que adquiriste la posesión con justo título y buena fe. No desde la firma del contrato sino desde que tomaste posesión real del inmueble. Escríbenos: 0994859814.</p></details>
<details><summary>¿La prescripción extraordinaria aplica para terrenos urbanos también?</summary><p class="faq-answer">Sí. Aplica tanto para terrenos urbanos como rurales. Los requisitos son los mismos en ambos casos. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo cambiar de la ordinaria a la extraordinaria si me rechazan la primera?</summary><p class="faq-answer">Puedes intentarlo con la extraordinaria si cumples los 15 años. Pero perderás el tiempo invertido en el primer juicio. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'despues-interrumpir-prescripcion-que-pasa-ecuador.html' `
'{"@type":"Question","name":"¿Cuándo empieza a contar el nuevo plazo de 15 años después de la interrupción?","acceptedAnswer":{"@type":"Answer","text":"Desde el momento en que el acto interruptivo dejó de producir efectos. Si fue una demanda, desde que se archivó o resolvió. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si interrumpo la prescripción el poseedor está obligado a salir del terreno?","acceptedAnswer":{"@type":"Answer","text":"No. La interrupción del plazo no lo obliga a salir. Solo reinicia el contador. Necesitas ganar el juicio para que salga. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La interrupción me sirve aunque no gane el juicio que la causó?","acceptedAnswer":{"@type":"Answer","text":"Sí. Aunque el juicio no prospere, el efecto interruptivo del plazo puede haberse producido igualmente si hubo notificación válida. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo interrumpir la prescripción varias veces?","acceptedAnswer":{"@type":"Answer","text":"Sí. Cada demanda válida interrumpe el plazo nuevamente. Pero solo interrumpir sin resolver el problema de fondo no es una solución definitiva. Escríbenos: 0994859814."}}' `
'<details><summary>¿Cuándo empieza a contar el nuevo plazo de 15 años después de la interrupción?</summary><p class="faq-answer">Desde el momento en que el acto interruptivo dejó de producir efectos. Si fue una demanda, desde que se archivó o resolvió. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si interrumpo la prescripción el poseedor está obligado a salir del terreno?</summary><p class="faq-answer">No. La interrupción del plazo no lo obliga a salir. Solo reinicia el contador. Necesitas ganar el juicio para que salga. Escríbenos: 0994859814.</p></details>
<details><summary>¿La interrupción me sirve aunque no gane el juicio que la causó?</summary><p class="faq-answer">Sí. Aunque el juicio no prospere, el efecto interruptivo del plazo puede haberse producido igualmente si hubo notificación válida. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo interrumpir la prescripción varias veces?</summary><p class="faq-answer">Sí. Cada demanda válida interrumpe el plazo nuevamente. Pero solo interrumpir sin resolver el problema de fondo no es una solución definitiva. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'terreno-sin-escritura-prescripcion-adquisitiva-ecuador.html' `
'{"@type":"Question","name":"¿Puedo hipotecar o vender el terreno mientras dura el juicio de prescripción?","acceptedAnswer":{"@type":"Answer","text":"No. Sin el título inscrito no puedes hacer esas operaciones. Debes esperar a que la sentencia se inscriba en el Registro de la Propiedad. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El terreno paga impuestos mientras no tengo escritura?","acceptedAnswer":{"@type":"Answer","text":"El impuesto predial lo paga quien aparece en el catastro. Pero pagar ese impuesto a tu nombre es una de las mejores pruebas de posesión. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si alguien ya inició otro juicio sobre el mismo terreno, puedo igual prescribir?","acceptedAnswer":{"@type":"Answer","text":"Depende del tipo de juicio. Un juicio previo sobre el mismo bien puede afectar tu proceso. Eso debe verificarse con un abogado antes de presentar la demanda. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si gano el juicio pero el terreno tiene deudas tributarias?","acceptedAnswer":{"@type":"Answer","text":"Las deudas tributarias que pesan sobre el bien pueden pasar al nuevo propietario. Es importante verificar si hay deudas pendientes antes de iniciar el proceso. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo hipotecar o vender el terreno mientras dura el juicio de prescripción?</summary><p class="faq-answer">No. Sin el título inscrito no puedes hacer esas operaciones. Debes esperar a que la sentencia se inscriba en el Registro de la Propiedad. Escríbenos: 0994859814.</p></details>
<details><summary>¿El terreno paga impuestos mientras no tengo escritura?</summary><p class="faq-answer">El impuesto predial lo paga quien aparece en el catastro. Pero pagar ese impuesto a tu nombre es una de las mejores pruebas de posesión. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si alguien ya inició otro juicio sobre el mismo terreno, puedo igual prescribir?</summary><p class="faq-answer">Depende del tipo de juicio. Un juicio previo sobre el mismo bien puede afectar tu proceso. Eso debe verificarse con un abogado antes de presentar la demanda. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si gano el juicio pero el terreno tiene deudas tributarias?</summary><p class="faq-answer">Las deudas tributarias que pesan sobre el bien pueden pasar al nuevo propietario. Es importante verificar si hay deudas pendientes antes de iniciar el proceso. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'abono-multa-transito-reinicia-prescripcion.html' `
'{"@type":"Question","name":"¿Si pagué $1 de $300 que debía, reinicié el plazo completo?","acceptedAnswer":{"@type":"Answer","text":"Cualquier pago parcial, por pequeño que sea, puede reiniciar el plazo de prescripción desde cero si quedó registrado en el sistema. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El pago de otro vehículo mío puede afectar la prescripción de esta multa?","acceptedAnswer":{"@type":"Answer","text":"No. Los pagos y prescripciones son independientes por cada multa. El pago de otra multa no afecta el plazo de la que quieres prescribir. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cómo verifico si hubo pagos anteriores que reiniciaron el plazo?","acceptedAnswer":{"@type":"Answer","text":"Consultando el historial de pagos en el portal de la ANT o del municipio correspondiente. También puedes pedir el reporte de movimientos de la multa directamente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo deshacer el efecto de un pago parcial para seguir con la prescripción?","acceptedAnswer":{"@type":"Answer","text":"No. El pago ya realizado reinició el plazo. Debes contar desde esa nueva fecha hacia los 5 años para calcular si ya volvió a prescribir. Escríbenos: 0994859814."}}' `
'<details><summary>¿Si pagué $1 de $300 que debía, reinicié el plazo completo?</summary><p class="faq-answer">Cualquier pago parcial, por pequeño que sea, puede reiniciar el plazo de prescripción desde cero si quedó registrado en el sistema. Escríbenos: 0994859814.</p></details>
<details><summary>¿El pago de otro vehículo mío puede afectar la prescripción de esta multa?</summary><p class="faq-answer">No. Los pagos y prescripciones son independientes por cada multa. El pago de otra multa no afecta el plazo de la que quieres prescribir. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cómo verifico si hubo pagos anteriores que reiniciaron el plazo?</summary><p class="faq-answer">Consultando el historial de pagos en el portal de la ANT o del municipio correspondiente. También puedes pedir el reporte de movimientos de la multa directamente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo deshacer el efecto de un pago parcial para seguir con la prescripción?</summary><p class="faq-answer">No. El pago ya realizado reinició el plazo. Debes contar desde esa nueva fecha hacia los 5 años para calcular si ya volvió a prescribir. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'ant-online-consultar-multas-ecuador.html' `
'{"@type":"Question","name":"¿Puedo consultar las multas en línea sin cédula?","acceptedAnswer":{"@type":"Answer","text":"No. El sistema de la ANT requiere el número de cédula del titular o la placa del vehículo para mostrar las multas registradas. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las multas del municipio aparecen en el portal de la ANT?","acceptedAnswer":{"@type":"Answer","text":"No siempre. Las multas municipales pueden estar en sistemas separados. La ANT registra las suyas; los municipios tienen sus propios portales. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué hago si no me aparece ninguna multa pero el SERT dice que sí tengo?","acceptedAnswer":{"@type":"Answer","text":"Puede haber rezago en los sistemas. Consulta directamente en las oficinas de la entidad emisora con tu cédula para obtener el reporte completo. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las multas prescritas todavía aparecen en el portal?","acceptedAnswer":{"@type":"Answer","text":"Sí, pueden seguir visibles aunque hayan prescrito. La visibilidad en el sistema no confirma que la multa sea exigible — solo un análisis legal determina si prescribió. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo consultar las multas en línea sin cédula?</summary><p class="faq-answer">No. El sistema de la ANT requiere el número de cédula del titular o la placa del vehículo para mostrar las multas registradas. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las multas del municipio aparecen en el portal de la ANT?</summary><p class="faq-answer">No siempre. Las multas municipales pueden estar en sistemas separados. La ANT registra las suyas; los municipios tienen sus propios portales. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué hago si no me aparece ninguna multa pero el SERT dice que sí tengo?</summary><p class="faq-answer">Puede haber rezago en los sistemas. Consulta directamente en las oficinas de la entidad emisora con tu cédula para obtener el reporte completo. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las multas prescritas todavía aparecen en el portal?</summary><p class="faq-answer">Sí, pueden seguir visibles aunque hayan prescrito. La visibilidad en el sistema no confirma que la multa sea exigible — solo un análisis legal determina si prescribió. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'ant-vs-municipio-quien-resuelve-prescripcion-multa.html' `
'{"@type":"Question","name":"¿Cómo sé si mi multa la emitió la ANT o el municipio?","acceptedAnswer":{"@type":"Answer","text":"Mirando la fuente que aparece en el documento de la multa o en el portal. Las multas de la ANT tienen código nacional; las municipales tienen código local de cada ciudad. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si presento la solicitud ante la entidad equivocada?","acceptedAnswer":{"@type":"Answer","text":"La rechazan por incompetencia y pierdes tiempo. Debes identificar bien la entidad emisora antes de presentar cualquier solicitud. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las multas de la Policía Nacional las resuelve la ANT o el municipio?","acceptedAnswer":{"@type":"Answer","text":"Ninguno. Las multas de la Policía Nacional tienen su propia sede de prescripción. Son un tercer grupo diferente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las multas anteriores a 2014 siempre son administrativas?","acceptedAnswer":{"@type":"Answer","text":"En general sí. Pero depende de la entidad emisora. Las de la Policía Nacional anteriores a 2014 también pueden tener un proceso diferente. Escríbenos: 0994859814."}}' `
'<details><summary>¿Cómo sé si mi multa la emitió la ANT o el municipio?</summary><p class="faq-answer">Mirando la fuente que aparece en el documento de la multa o en el portal. Las multas de la ANT tienen código nacional; las municipales tienen código local de cada ciudad. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si presento la solicitud ante la entidad equivocada?</summary><p class="faq-answer">La rechazan por incompetencia y pierdes tiempo. Debes identificar bien la entidad emisora antes de presentar cualquier solicitud. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las multas de la Policía Nacional las resuelve la ANT o el municipio?</summary><p class="faq-answer">Ninguno. Las multas de la Policía Nacional tienen su propia sede de prescripción. Son un tercer grupo diferente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las multas anteriores a 2014 siempre son administrativas?</summary><p class="faq-answer">En general sí. Pero depende de la entidad emisora. Las de la Policía Nacional anteriores a 2014 también pueden tener un proceso diferente. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'buro-credito-multa-transito-ecuador.html' `
'{"@type":"Question","name":"¿Si prescribo la multa, desaparece del buró de crédito?","acceptedAnswer":{"@type":"Answer","text":"La prescripción elimina la deuda administrativa. Si había una anotación en el buró por esa causa, también debería limpiarse. Consulta con Juristam para verificar tu caso. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿En cuánto tiempo puede el cobro coactivo afectar el buró?","acceptedAnswer":{"@type":"Answer","text":"Una vez que la entidad inicia cobranza judicial, puede notificarse al sistema de riesgos. El tiempo varía pero puede ocurrir en semanas desde que se inicia el proceso. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo acceder a crédito aunque tenga una multa de tránsito pendiente?","acceptedAnswer":{"@type":"Answer","text":"Depende del banco y del monto. Multas pequeñas pueden no afectar. Pero si hay cobro coactivo registrado, la aprobación de crédito se complica significativamente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La multa prescrita queda limpia en todos los sistemas incluyendo el buró?","acceptedAnswer":{"@type":"Answer","text":"La prescripción elimina la acción de cobro. Si hubo anotación en el buró relacionada, corresponde solicitar también la actualización de esa información. Escríbenos: 0994859814."}}' `
'<details><summary>¿Si prescribo la multa, desaparece del buró de crédito?</summary><p class="faq-answer">La prescripción elimina la deuda administrativa. Si había una anotación en el buró por esa causa, también debería limpiarse. Consulta con Juristam para verificar tu caso. Escríbenos: 0994859814.</p></details>
<details><summary>¿En cuánto tiempo puede el cobro coactivo afectar el buró?</summary><p class="faq-answer">Una vez que la entidad inicia cobranza judicial, puede notificarse al sistema de riesgos. El tiempo varía pero puede ocurrir en semanas desde que se inicia el proceso. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo acceder a crédito aunque tenga una multa de tránsito pendiente?</summary><p class="faq-answer">Depende del banco y del monto. Multas pequeñas pueden no afectar. Pero si hay cobro coactivo registrado, la aprobación de crédito se complica significativamente. Escríbenos: 0994859814.</p></details>
<details><summary>¿La multa prescrita queda limpia en todos los sistemas incluyendo el buró?</summary><p class="faq-answer">La prescripción elimina la acción de cobro. Si hubo anotación en el buró relacionada, corresponde solicitar también la actualización de esa información. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'calcular-prescripcion-multa-transito-ecuador.html' `
'{"@type":"Question","name":"¿Si no sé la fecha exacta de la infracción cómo calculo el plazo?","acceptedAnswer":{"@type":"Answer","text":"Consultando el historial en el portal de la ANT o del municipio. La fecha de la infracción siempre está registrada en el sistema aunque no la recuerdes. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El plazo es el mismo para todos los tipos de multa de tránsito?","acceptedAnswer":{"@type":"Answer","text":"Sí. El plazo general es de 5 años para todas las multas de tránsito en Ecuador, independientemente del tipo de infracción. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si la multa fue por accidente con daños, el plazo es diferente?","acceptedAnswer":{"@type":"Answer","text":"Las multas administrativas de tránsito tienen el plazo estándar. Las acciones civiles por daños del accidente tienen plazos distintos. Son cosas separadas. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo calcular el plazo yo mismo sin abogado?","acceptedAnswer":{"@type":"Answer","text":"Puedes hacer el cálculo básico: fecha de infracción más 5 años. Pero verificar si hubo interrupciones válidas en ese período requiere un análisis más técnico. Escríbenos: 0994859814."}}' `
'<details><summary>¿Si no sé la fecha exacta de la infracción cómo calculo el plazo?</summary><p class="faq-answer">Consultando el historial en el portal de la ANT o del municipio. La fecha de la infracción siempre está registrada en el sistema aunque no la recuerdes. Escríbenos: 0994859814.</p></details>
<details><summary>¿El plazo es el mismo para todos los tipos de multa de tránsito?</summary><p class="faq-answer">Sí. El plazo general es de 5 años para todas las multas de tránsito en Ecuador, independientemente del tipo de infracción. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si la multa fue por accidente con daños, el plazo es diferente?</summary><p class="faq-answer">Las multas administrativas de tránsito tienen el plazo estándar. Las acciones civiles por daños del accidente tienen plazos distintos. Son cosas separadas. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo calcular el plazo yo mismo sin abogado?</summary><p class="faq-answer">Puedes hacer el cálculo básico: fecha de infracción más 5 años. Pero verificar si hubo interrupciones válidas en ese período requiere un análisis más técnico. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'cual-prescripcion-aplica-mi-caso-ecuador.html' `
'{"@type":"Question","name":"¿Cómo sé si mi multa es anterior o posterior a 2014?","acceptedAnswer":{"@type":"Answer","text":"La fecha de la infracción aparece en el documento de la multa y en el sistema de la entidad emisora. Si es de 2013 o antes, aplica la vía administrativa. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si tengo multas de antes y después de 2014?","acceptedAnswer":{"@type":"Answer","text":"Cada multa se tramita por la vía que corresponde a su fecha. Si tienes multas de ambos períodos, puede ser necesario tramitar en dos sedes distintas. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo equivocarme de vía y qué consecuencias tiene?","acceptedAnswer":{"@type":"Answer","text":"Si presentas en la vía incorrecta te la rechazan por incompetencia. No hay sanción, pero pierdes tiempo valioso. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La vía depende de la entidad emisora o de la fecha de la multa?","acceptedAnswer":{"@type":"Answer","text":"Principalmente de la fecha. Las multas desde 2014 van al Juez de Contravenciones independientemente de si las emitió la ANT, el municipio o la Policía. Escríbenos: 0994859814."}}' `
'<details><summary>¿Cómo sé si mi multa es anterior o posterior a 2014?</summary><p class="faq-answer">La fecha de la infracción aparece en el documento de la multa y en el sistema de la entidad emisora. Si es de 2013 o antes, aplica la vía administrativa. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si tengo multas de antes y después de 2014?</summary><p class="faq-answer">Cada multa se tramita por la vía que corresponde a su fecha. Si tienes multas de ambos períodos, puede ser necesario tramitar en dos sedes distintas. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo equivocarme de vía y qué consecuencias tiene?</summary><p class="faq-answer">Si presentas en la vía incorrecta te la rechazan por incompetencia. No hay sanción, pero pierdes tiempo valioso. Escríbenos: 0994859814.</p></details>
<details><summary>¿La vía depende de la entidad emisora o de la fecha de la multa?</summary><p class="faq-answer">Principalmente de la fecha. Las multas desde 2014 van al Juez de Contravenciones independientemente de si las emitió la ANT, el municipio o la Policía. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'cuantas-multas-tengo-transito-ecuador.html' `
'{"@type":"Question","name":"¿Puedo pedir el historial completo de multas en la ANT en persona?","acceptedAnswer":{"@type":"Answer","text":"Sí. Puedes acudir a las oficinas de la ANT con tu cédula y solicitar un reporte de todas tus multas registradas en el sistema nacional. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué hago si encuentro multas que no reconozco como mías?","acceptedAnswer":{"@type":"Answer","text":"Puede haber errores del sistema o multas del nuevo dueño de un vehículo que vendiste. Debes identificar el origen para determinar si te corresponde o hay un error. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las multas pagadas desaparecen del historial?","acceptedAnswer":{"@type":"Answer","text":"Las multas pagadas quedan registradas como pagadas pero no desaparecen del historial. Solo interesan las que están pendientes para efectos de prescripción. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo ver el historial de multas de un vehículo que ya vendí?","acceptedAnswer":{"@type":"Answer","text":"Si el vehículo estuvo a tu nombre, sus multas pasadas pueden seguir vinculadas a tu historial. Verifica si el traspaso fue correcto y si las multas anteriores a la venta son de tu responsabilidad. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo pedir el historial completo de multas en la ANT en persona?</summary><p class="faq-answer">Sí. Puedes acudir a las oficinas de la ANT con tu cédula y solicitar un reporte de todas tus multas registradas en el sistema nacional. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué hago si encuentro multas que no reconozco como mías?</summary><p class="faq-answer">Puede haber errores del sistema o multas del nuevo dueño de un vehículo que vendiste. Debes identificar el origen para determinar si te corresponde o hay un error. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las multas pagadas desaparecen del historial?</summary><p class="faq-answer">Las multas pagadas quedan registradas como pagadas pero no desaparecen del historial. Solo interesan las que están pendientes para efectos de prescripción. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo ver el historial de multas de un vehículo que ya vendí?</summary><p class="faq-answer">Si el vehículo estuvo a tu nombre, sus multas pasadas pueden seguir vinculadas a tu historial. Verifica si el traspaso fue correcto y si las multas anteriores a la venta son de tu responsabilidad. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'cuantos-puntos-tiene-mi-licencia-ecuador.html' `
'{"@type":"Question","name":"¿El sistema de puntos aplica a todos los tipos de licencia?","acceptedAnswer":{"@type":"Answer","text":"Sí. El sistema de puntos aplica a todas las categorías de licencia de conducir en Ecuador, desde la categoría B hasta las profesionales. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo ver el historial de infracciones que me descontaron los puntos?","acceptedAnswer":{"@type":"Answer","text":"Sí. En el portal de la ANT puedes ver no solo los puntos actuales sino también el historial de las infracciones que generaron los descuentos. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Los puntos vuelven solos con el tiempo?","acceptedAnswer":{"@type":"Answer","text":"No. En Ecuador los puntos no se recuperan automáticamente con el tiempo. Debes hacer el curso de recuperación para que te sean restituidos. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuántos puntos tiene una licencia nueva en Ecuador?","acceptedAnswer":{"@type":"Answer","text":"Una licencia nueva empieza con 30 puntos. Las infracciones descuentan puntos y al llegar a cero la licencia queda inhabilitada. Escríbenos: 0994859814."}}' `
'<details><summary>¿El sistema de puntos aplica a todos los tipos de licencia?</summary><p class="faq-answer">Sí. El sistema de puntos aplica a todas las categorías de licencia de conducir en Ecuador, desde la categoría B hasta las profesionales. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo ver el historial de infracciones que me descontaron los puntos?</summary><p class="faq-answer">Sí. En el portal de la ANT puedes ver no solo los puntos actuales sino también el historial de las infracciones que generaron los descuentos. Escríbenos: 0994859814.</p></details>
<details><summary>¿Los puntos vuelven solos con el tiempo?</summary><p class="faq-answer">No. En Ecuador los puntos no se recuperan automáticamente con el tiempo. Debes hacer el curso de recuperación para que te sean restituidos. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuántos puntos tiene una licencia nueva en Ecuador?</summary><p class="faq-answer">Una licencia nueva empieza con 30 puntos. Las infracciones descuentan puntos y al llegar a cero la licencia queda inhabilitada. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'escrito-prescripcion-contravenciones-requisitos.html' `
'{"@type":"Question","name":"¿El escrito debe ser redactado por abogado o yo puedo hacerlo?","acceptedAnswer":{"@type":"Answer","text":"La vía judicial ante el Juez de Contravenciones requiere patrocinio de abogado. No puedes presentarlo como persona natural sin representación legal. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si el escrito tiene errores formales?","acceptedAnswer":{"@type":"Answer","text":"El juez puede rechazarlo o pedir que lo corrijas en un plazo corto. Si el plazo de prescripción vence mientras tanto, puedes perder el derecho. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuántos días tarda el juez en resolver la solicitud de prescripción?","acceptedAnswer":{"@type":"Answer","text":"Varía por juzgado y carga procesal. En promedio entre 30 y 90 días. Algunos casos se resuelven más rápido si hay menos carga en el juzgado. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo presentar el escrito de forma digital?","acceptedAnswer":{"@type":"Answer","text":"Algunas unidades judiciales ya aceptan escritos digitales firmados electrónicamente. Pero esto depende del juzgado específico y la ciudad. Escríbenos: 0994859814."}}' `
'<details><summary>¿El escrito debe ser redactado por abogado o yo puedo hacerlo?</summary><p class="faq-answer">La vía judicial ante el Juez de Contravenciones requiere patrocinio de abogado. No puedes presentarlo como persona natural sin representación legal. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si el escrito tiene errores formales?</summary><p class="faq-answer">El juez puede rechazarlo o pedir que lo corrijas en un plazo corto. Si el plazo de prescripción vence mientras tanto, puedes perder el derecho. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuántos días tarda el juez en resolver la solicitud de prescripción?</summary><p class="faq-answer">Varía por juzgado y carga procesal. En promedio entre 30 y 90 días. Algunos casos se resuelven más rápido si hay menos carga en el juzgado. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo presentar el escrito de forma digital?</summary><p class="faq-answer">Algunas unidades judiciales ya aceptan escritos digitales firmados electrónicamente. Pero esto depende del juzgado específico y la ciudad. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'escrito-prescripcion-juez-contravenciones-transito.html' `
'{"@type":"Question","name":"¿El escrito para el juez es diferente al que se presenta en la ANT?","acceptedAnswer":{"@type":"Answer","text":"Sí, son completamente diferentes. El escrito judicial es más formal, requiere fundamentación legal, citación de normas y firma de abogado. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Necesito presentar todos los documentos juntos con el escrito?","acceptedAnswer":{"@type":"Answer","text":"Sí. El escrito judicial debe acompañarse de todos los documentos de sustento desde la primera presentación. No puedes presentarlos después en etapas separadas. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué norma legal debo citar en el escrito?","acceptedAnswer":{"@type":"Answer","text":"El artículo correspondiente del COIP o la LOTTTSV según corresponda, más la jurisprudencia aplicable. Tu abogado determinará las normas exactas. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuánto tiempo tiene el juez para calificar la solicitud?","acceptedAnswer":{"@type":"Answer","text":"El código establece plazos procesales específicos. Si el juez no califica en el plazo legal, tu abogado puede hacer el llamado de atención correspondiente. Escríbenos: 0994859814."}}' `
'<details><summary>¿El escrito para el juez es diferente al que se presenta en la ANT?</summary><p class="faq-answer">Sí, son completamente diferentes. El escrito judicial es más formal, requiere fundamentación legal, citación de normas y firma de abogado. Escríbenos: 0994859814.</p></details>
<details><summary>¿Necesito presentar todos los documentos juntos con el escrito?</summary><p class="faq-answer">Sí. El escrito judicial debe acompañarse de todos los documentos de sustento desde la primera presentación. No puedes presentarlos después en etapas separadas. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué norma legal debo citar en el escrito?</summary><p class="faq-answer">El artículo correspondiente del COIP o la LOTTTSV según corresponda, más la jurisprudencia aplicable. Tu abogado determinará las normas exactas. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuánto tiempo tiene el juez para calificar la solicitud?</summary><p class="faq-answer">El código establece plazos procesales específicos. Si el juez no califica en el plazo legal, tu abogado puede hacer el llamado de atención correspondiente. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'multa-movidelnor-prescripcion-ecuador.html' `
'{"@type":"Question","name":"¿Movidelnor emite multas en todas las provincias del norte?","acceptedAnswer":{"@type":"Answer","text":"Movidelnor opera en Imbabura, Carchi y Esmeraldas. Si tu multa fue emitida en esas provincias por esa entidad, el proceso de prescripción tiene sus particularidades. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las multas de Movidelnor también prescriben en 5 años?","acceptedAnswer":{"@type":"Answer","text":"Sí. El plazo de prescripción de 5 años aplica para las multas de Movidelnor igual que para las de otras entidades. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo tramitar la prescripción de una multa de Movidelnor desde otra ciudad?","acceptedAnswer":{"@type":"Answer","text":"En muchos casos sí. El abogado puede gestionar el proceso sin que necesites viajar a la provincia donde se emitió la multa. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las multas de Movidelnor anteriores a 2014 son administrativas?","acceptedAnswer":{"@type":"Answer","text":"Sí, las anteriores a 2014 siguen la vía administrativa. Las posteriores requieren el proceso ante el Juez de Contravenciones. Escríbenos: 0994859814."}}' `
'<details><summary>¿Movidelnor emite multas en todas las provincias del norte?</summary><p class="faq-answer">Movidelnor opera en Imbabura, Carchi y Esmeraldas. Si tu multa fue emitida en esas provincias por esa entidad, el proceso de prescripción tiene sus particularidades. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las multas de Movidelnor también prescriben en 5 años?</summary><p class="faq-answer">Sí. El plazo de prescripción de 5 años aplica para las multas de Movidelnor igual que para las de otras entidades. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo tramitar la prescripción de una multa de Movidelnor desde otra ciudad?</summary><p class="faq-answer">En muchos casos sí. El abogado puede gestionar el proceso sin que necesites viajar a la provincia donde se emitió la multa. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las multas de Movidelnor anteriores a 2014 son administrativas?</summary><p class="faq-answer">Sí, las anteriores a 2014 siguen la vía administrativa. Las posteriores requieren el proceso ante el Juez de Contravenciones. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'multa-portovial-prescripcion-ecuador.html' `
'{"@type":"Question","name":"¿Las multas de Portovial son de tránsito o de otro tipo?","acceptedAnswer":{"@type":"Answer","text":"Portovial emite multas de tránsito en las vías de la provincia del Guayas. Se rigen por las mismas normas de prescripción que otras multas de tránsito. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El plazo de 5 años de las multas de Portovial es igual al de las de la ANT?","acceptedAnswer":{"@type":"Answer","text":"Sí. El plazo general de prescripción de 5 años aplica a las multas de Portovial igual que a las de la ANT o los municipios. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Dónde presento la solicitud de prescripción de una multa de Portovial?","acceptedAnswer":{"@type":"Answer","text":"Depende de la fecha de la multa. Las anteriores a 2014 van en sede administrativa; las posteriores ante el Juez de Contravenciones competente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo tramitar la prescripción de una multa de Portovial desde Quito?","acceptedAnswer":{"@type":"Answer","text":"Con apoyo legal sí. En Juristam gestionamos el proceso de prescripción en provincias aunque estés en otra ciudad. Escríbenos: 0994859814."}}' `
'<details><summary>¿Las multas de Portovial son de tránsito o de otro tipo?</summary><p class="faq-answer">Portovial emite multas de tránsito en las vías de la provincia del Guayas. Se rigen por las mismas normas de prescripción que otras multas de tránsito. Escríbenos: 0994859814.</p></details>
<details><summary>¿El plazo de 5 años de las multas de Portovial es igual al de las de la ANT?</summary><p class="faq-answer">Sí. El plazo general de prescripción de 5 años aplica a las multas de Portovial igual que a las de la ANT o los municipios. Escríbenos: 0994859814.</p></details>
<details><summary>¿Dónde presento la solicitud de prescripción de una multa de Portovial?</summary><p class="faq-answer">Depende de la fecha de la multa. Las anteriores a 2014 van en sede administrativa; las posteriores ante el Juez de Contravenciones competente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo tramitar la prescripción de una multa de Portovial desde Quito?</summary><p class="faq-answer">Con apoyo legal sí. En Juristam gestionamos el proceso de prescripción en provincias aunque estés en otra ciudad. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'multa-transito-2021-prescripcion-ecuador.html' `
'{"@type":"Question","name":"¿Las multas de 2021 ya prescribieron en 2026?","acceptedAnswer":{"@type":"Answer","text":"Si fueron emitidas antes del 30 de mayo de 2021 y no hubo cobro judicial válido, ya cumplieron los 5 años. Consulta para verificar tu caso específico. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las multas de tránsito de 2021 se tramitan en sede administrativa o judicial?","acceptedAnswer":{"@type":"Answer","text":"Las de 2021 son posteriores a 2014, por lo que corresponden a la vía judicial ante el Juez de Contravenciones. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El COVID-19 de 2020-2021 afectó el conteo del plazo de prescripción?","acceptedAnswer":{"@type":"Answer","text":"Las restricciones de movilidad del COVID no suspendieron los plazos de prescripción de multas de tránsito en Ecuador. El plazo siguió corriendo. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si ya pagué parte de la multa de 2021 aún puedo prescribir el resto?","acceptedAnswer":{"@type":"Answer","text":"No. El pago parcial reinició el plazo desde la fecha de ese pago. Debe calcularse desde ese momento, no desde la fecha original de la multa. Escríbenos: 0994859814."}}' `
'<details><summary>¿Las multas de 2021 ya prescribieron en 2026?</summary><p class="faq-answer">Si fueron emitidas antes del 30 de mayo de 2021 y no hubo cobro judicial válido, ya cumplieron los 5 años. Consulta para verificar tu caso específico. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las multas de tránsito de 2021 se tramitan en sede administrativa o judicial?</summary><p class="faq-answer">Las de 2021 son posteriores a 2014, por lo que corresponden a la vía judicial ante el Juez de Contravenciones. Escríbenos: 0994859814.</p></details>
<details><summary>¿El COVID-19 de 2020-2021 afectó el conteo del plazo de prescripción?</summary><p class="faq-answer">Las restricciones de movilidad del COVID no suspendieron los plazos de prescripción de multas de tránsito en Ecuador. El plazo siguió corriendo. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si ya pagué parte de la multa de 2021 aún puedo prescribir el resto?</summary><p class="faq-answer">No. El pago parcial reinició el plazo desde la fecha de ese pago. Debe calcularse desde ese momento, no desde la fecha original de la multa. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'multa-transito-interes-mora-ecuador.html' `
'{"@type":"Question","name":"¿Cómo se calculan los intereses de mora en multas de tránsito?","acceptedAnswer":{"@type":"Answer","text":"Se calculan sobre el capital de la multa aplicando la tasa de interés legal vigente. La entidad emisora lleva ese cálculo actualizado en su sistema. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si la multa prescribe también prescriben los intereses acumulados?","acceptedAnswer":{"@type":"Answer","text":"Sí. La prescripción extingue tanto el capital de la multa como los intereses acumulados. No quedan obligaciones pendientes tras la prescripción. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo ver cuánto han crecido los intereses de mi multa?","acceptedAnswer":{"@type":"Answer","text":"Puedes solicitar a la entidad emisora el estado de cuenta de la multa con el desglose de capital e intereses acumulados a la fecha. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si pago solo el capital y no los intereses, la multa se cancela?","acceptedAnswer":{"@type":"Answer","text":"No. Para cancelar una multa debes pagar el total incluyendo intereses. Un pago solo del capital no extingue la obligación completa. Escríbenos: 0994859814."}}' `
'<details><summary>¿Cómo se calculan los intereses de mora en multas de tránsito?</summary><p class="faq-answer">Se calculan sobre el capital de la multa aplicando la tasa de interés legal vigente. La entidad emisora lleva ese cálculo actualizado en su sistema. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si la multa prescribe también prescriben los intereses acumulados?</summary><p class="faq-answer">Sí. La prescripción extingue tanto el capital de la multa como los intereses acumulados. No quedan obligaciones pendientes tras la prescripción. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo ver cuánto han crecido los intereses de mi multa?</summary><p class="faq-answer">Puedes solicitar a la entidad emisora el estado de cuenta de la multa con el desglose de capital e intereses acumulados a la fecha. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si pago solo el capital y no los intereses, la multa se cancela?</summary><p class="faq-answer">No. Para cancelar una multa debes pagar el total incluyendo intereses. Un pago solo del capital no extingue la obligación completa. Escríbenos: 0994859814.</p></details>'

Write-Host "`n=== DONE === Updated=$($updated) | Skipped=$($skipped) | NotFound=$($notFound)"
