$blogDir = 'c:\Users\HOLA\OneDrive\Escritorio\juristam-web\blog'
$utf8noBOM = New-Object System.Text.UTF8Encoding $false
$updated = 0; $skipped = 0; $notFound = 0

function Find-ArrayClose($str, $startPos) {
    $openPos = $str.IndexOf('[', $startPos)
    if ($openPos -lt 0) { return -1 }
    $depth = 0; $inStr = $false; $esc = $false
    $bsc = [int][char]92; $dqc = [int][char]34
    for ($i = $openPos; $i -lt $str.Length; $i++) {
        $ci = [int][char]$str[$i]
        if ($esc) { $esc = $false; continue }
        if ($ci -eq $bsc -and $inStr) { $esc = $true; continue }
        if ($ci -eq $dqc) { $inStr = !$inStr; continue }
        if (-not $inStr) {
            if ($str[$i] -eq '[') { $depth++ }
            elseif ($str[$i] -eq ']') { $depth--; if ($depth -eq 0) { return $i } }
        }
    }
    return -1
}

function Add-FaqData($filename, $jsonAdd, $htmlAdd) {
    $path = Join-Path $blogDir $filename
    if (-not (Test-Path $path)) { $script:notFound++; Write-Host "NOT FOUND: $filename"; return }
    $c = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
    $marker = $jsonAdd.Substring(0,[Math]::Min(50,$jsonAdd.Length))
    if ($c.IndexOf($marker) -ge 0) { $script:skipped++; Write-Host "SKIP: $filename"; return }
    $tag = '<script type="application/ld+json">'
    $si = $c.IndexOf($tag); $ei = $c.IndexOf('</script>', $si)
    if ($si -ge 0) {
        $jb = $c.Substring($si+$tag.Length, $ei-$si-$tag.Length)
        $fp = $jb.IndexOf('"FAQPage"')
        if ($fp -ge 0) {
            $mp = $jb.IndexOf('"mainEntity"', $fp)
            $cl = Find-ArrayClose $jb $mp
            if ($cl -ge 0) {
                $abs = $si+$tag.Length+$cl
                $c = $c.Substring(0,$abs) + ',' + $jsonAdd + $c.Substring($abs)
            }
        }
    }
    $ld = $c.LastIndexOf('</details>')
    if ($ld -ge 0) {
        $cd = $c.IndexOf('</div>', $ld+10)
        if ($cd -ge 0) { $c = $c.Substring(0,$cd) + $htmlAdd + "`n" + $c.Substring($cd) }
    }
    [System.IO.File]::WriteAllText($path, $c, $utf8noBOM)
    $script:updated++; Write-Host "OK: $filename"
}

Add-FaqData 'posesion-continua-ininterrumpida-como-probarla-ecuador.html' `
'{"@type":"Question","name":"¿Ausencias por trabajo en otra ciudad interrumpen la posesión?","acceptedAnswer":{"@type":"Answer","text":"No necesariamente. Si mantuviste el terreno, pagaste el predial y volvías periódicamente, la posesión puede considerarse continua. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La pandemia del COVID pudo interrumpir la posesión en 2020?","acceptedAnswer":{"@type":"Answer","text":"Las restricciones de movilidad no interrumpen automáticamente la posesión. Lo que importa es que no hayas abandonado el terreno de forma definitiva. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cómo pruebo que la posesión fue continua durante 15 años?","acceptedAnswer":{"@type":"Answer","text":"Combinando documentos de distintos años: prediales, fotos, testimonios de vecinos, servicios básicos y documentos municipales. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si alguien me expulsó temporalmente del terreno, se interrumpe?","acceptedAnswer":{"@type":"Answer","text":"Depende. Si fue una turbación pasajera que no duró más de un año, puede no interrumpir. Si duró más y no actuaste legalmente, sí puede afectar. Escríbenos: 0994859814."}}' `
'<details><summary>¿Ausencias por trabajo en otra ciudad interrumpen la posesión?</summary><p class="faq-answer">No necesariamente. Si mantuviste el terreno, pagaste el predial y volvías periódicamente, la posesión puede considerarse continua. Escríbenos: 0994859814.</p></details>
<details><summary>¿La pandemia del COVID pudo interrumpir la posesión en 2020?</summary><p class="faq-answer">Las restricciones de movilidad no interrumpen automáticamente la posesión. Lo que importa es que no hayas abandonado el terreno de forma definitiva. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cómo pruebo que la posesión fue continua durante 15 años?</summary><p class="faq-answer">Combinando documentos de distintos años: prediales, fotos, testimonios de vecinos, servicios básicos y documentos municipales. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si alguien me expulsó temporalmente del terreno, se interrumpe?</summary><p class="faq-answer">Depende. Si fue una turbación pasajera que no duró más de un año, puede no interrumpir. Si duró más y no actuaste legalmente, sí puede afectar. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'posesion-continua-interrupciones-ecuador.html' `
'{"@type":"Question","name":"¿Una pelea con el vecino sobre los linderos interrumpe la posesión?","acceptedAnswer":{"@type":"Answer","text":"Un conflicto verbal o disputa de linderos no interrumpe la posesión. Solo la pérdida física del control o un acto judicial en tu contra lo hace. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si el terreno fue inundado y no pude entrar por meses, se interrumpe?","acceptedAnswer":{"@type":"Answer","text":"Los casos de fuerza mayor generalmente no interrumpen la posesión porque no dependen de tu voluntad. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si el propietario entró al terreno sin ir a juicio, interrumpe?","acceptedAnswer":{"@type":"Answer","text":"Si logró expulsarte físicamente de forma efectiva y no recuperaste la posesión en el año siguiente, puede considerarse interrupción. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La interrupción natural y la civil son lo mismo?","acceptedAnswer":{"@type":"Answer","text":"No. La natural es la pérdida física del terreno. La civil es un acto jurídico como una demanda. Ambas tienen efectos similares sobre el plazo pero operan diferente. Escríbenos: 0994859814."}}' `
'<details><summary>¿Una pelea con el vecino sobre los linderos interrumpe la posesión?</summary><p class="faq-answer">Un conflicto verbal o disputa de linderos no interrumpe la posesión. Solo la pérdida física del control o un acto judicial en tu contra lo hace. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si el terreno fue inundado y no pude entrar por meses, se interrumpe?</summary><p class="faq-answer">Los casos de fuerza mayor generalmente no interrumpen la posesión porque no dependen de tu voluntad. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si el propietario entró al terreno sin ir a juicio, interrumpe?</summary><p class="faq-answer">Si logró expulsarte físicamente de forma efectiva y no recuperaste la posesión en el año siguiente, puede considerarse interrupción. Escríbenos: 0994859814.</p></details>
<details><summary>¿La interrupción natural y la civil son lo mismo?</summary><p class="faq-answer">No. La natural es la pérdida física del terreno. La civil es un acto jurídico como una demanda. Ambas tienen efectos similares sobre el plazo pero operan diferente. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'posesion-efectiva-vs-prescripcion-adquisitiva-ecuador.html' `
'{"@type":"Question","name":"¿Cuándo necesito posesión efectiva y cuándo prescripción adquisitiva?","acceptedAnswer":{"@type":"Answer","text":"La posesión efectiva la necesitas cuando heredas bienes de alguien fallecido. La prescripción adquisitiva cuando quieres ganar la propiedad por años de posesión. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La posesión efectiva me da título de propiedad del terreno?","acceptedAnswer":{"@type":"Answer","text":"No. La posesión efectiva reconoce que eres heredero, pero el terreno sigue sin escritura a tu nombre. Para eso necesitas trámites adicionales. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo hacer ambos procesos al mismo tiempo?","acceptedAnswer":{"@type":"Answer","text":"Sí. Si heredaste la posesión de un familiar, puedes tramitar la posesión efectiva y simultáneamente iniciar el juicio de prescripción. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuánto cuesta la posesión efectiva en Ecuador?","acceptedAnswer":{"@type":"Answer","text":"Es un trámite notarial o judicial con costos variables según el número de herederos y los bienes involucrados. Consulta para un presupuesto según tu caso. Escríbenos: 0994859814."}}' `
'<details><summary>¿Cuándo necesito posesión efectiva y cuándo prescripción adquisitiva?</summary><p class="faq-answer">La posesión efectiva la necesitas cuando heredas bienes de alguien fallecido. La prescripción adquisitiva cuando quieres ganar la propiedad por años de posesión. Escríbenos: 0994859814.</p></details>
<details><summary>¿La posesión efectiva me da título de propiedad del terreno?</summary><p class="faq-answer">No. La posesión efectiva reconoce que eres heredero, pero el terreno sigue sin escritura a tu nombre. Para eso necesitas trámites adicionales. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo hacer ambos procesos al mismo tiempo?</summary><p class="faq-answer">Sí. Si heredaste la posesión de un familiar, puedes tramitar la posesión efectiva y simultáneamente iniciar el juicio de prescripción. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuánto cuesta la posesión efectiva en Ecuador?</summary><p class="faq-answer">Es un trámite notarial o judicial con costos variables según el número de herederos y los bienes involucrados. Consulta para un presupuesto según tu caso. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'posesion-pacifica-requisito-ecuador.html' `
'{"@type":"Question","name":"¿Una demanda del propietario destruye la posesión pacífica?","acceptedAnswer":{"@type":"Answer","text":"La demanda en sí no la destruye, pero si resulta en una orden que te expulsa del terreno, sí puede afectar la pacificidad. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Una pelea física en el terreno destruye la posesión pacífica?","acceptedAnswer":{"@type":"Answer","text":"Depende de la gravedad. Un incidente aislado puede no destruirla. Un patrón de violencia para mantenerse en el terreno sí puede afectarla. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cómo demuestro ante el juez que mi posesión fue pacífica?","acceptedAnswer":{"@type":"Answer","text":"Con la ausencia de antecedentes penales relacionados al terreno, testimonios de vecinos, y la falta de demandas previas en tu contra sobre ese predio. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si el propietario vino a amenazarme verbalmente, afecta mi posesión pacífica?","acceptedAnswer":{"@type":"Answer","text":"No. Las amenazas verbales del propietario no afectan la calificación de tu posesión. Lo que importa es cómo tú la obtuviste y mantuviste. Escríbenos: 0994859814."}}' `
'<details><summary>¿Una demanda del propietario destruye la posesión pacífica?</summary><p class="faq-answer">La demanda en sí no la destruye, pero si resulta en una orden que te expulsa del terreno, sí puede afectar la pacificidad. Escríbenos: 0994859814.</p></details>
<details><summary>¿Una pelea física en el terreno destruye la posesión pacífica?</summary><p class="faq-answer">Depende de la gravedad. Un incidente aislado puede no destruirla. Un patrón de violencia para mantenerse en el terreno sí puede afectarla. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cómo demuestro ante el juez que mi posesión fue pacífica?</summary><p class="faq-answer">Con la ausencia de antecedentes penales relacionados al terreno, testimonios de vecinos, y la falta de demandas previas en tu contra sobre ese predio. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si el propietario vino a amenazarme verbalmente, afecta mi posesión pacífica?</summary><p class="faq-answer">No. Las amenazas verbales del propietario no afectan la calificación de tu posesión. Lo que importa es cómo tú la obtuviste y mantuviste. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'posesion-publica-que-significa-ecuador.html' `
'{"@type":"Question","name":"¿Si poseo el terreno en silencio sin que nadie lo sepa, no califica?","acceptedAnswer":{"@type":"Answer","text":"Exactamente. La posesión clandestina no cuenta para la prescripción. Debes haber actuado visiblemente como si fuera tuyo. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cómo demuestro que mi posesión fue pública?","acceptedAnswer":{"@type":"Answer","text":"Con testimonios de vecinos, fotos donde se ve el terreno habitado o trabajado, permisos municipales y pago de prediales. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si construí dentro sin que se vea desde la calle, es pública?","acceptedAnswer":{"@type":"Answer","text":"Si la comunidad cercana sabía que tú estabas ahí aunque no se vea desde la calle, puede calificar. La publicidad no requiere visibilidad desde la vía pública. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Los vecinos que dicen que no me conocen pueden arruinar el caso?","acceptedAnswer":{"@type":"Answer","text":"Un solo testigo hostil no destruye el caso. Si otros vecinos y documentos confirman tu posesión, el juez puede desestimar ese testimonio. Escríbenos: 0994859814."}}' `
'<details><summary>¿Si poseo el terreno en silencio sin que nadie lo sepa, no califica?</summary><p class="faq-answer">Exactamente. La posesión clandestina no cuenta para la prescripción. Debes haber actuado visiblemente como si fuera tuyo. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cómo demuestro que mi posesión fue pública?</summary><p class="faq-answer">Con testimonios de vecinos, fotos donde se ve el terreno habitado o trabajado, permisos municipales y pago de prediales. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si construí dentro sin que se vea desde la calle, es pública?</summary><p class="faq-answer">Si la comunidad cercana sabía que tú estabas ahí aunque no se vea desde la calle, puede calificar. La publicidad no requiere visibilidad desde la vía pública. Escríbenos: 0994859814.</p></details>
<details><summary>¿Los vecinos que dicen que no me conocen pueden arruinar el caso?</summary><p class="faq-answer">Un solo testigo hostil no destruye el caso. Si otros vecinos y documentos confirman tu posesión, el juez puede desestimar ese testimonio. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'prescripcion-adquisitiva-bien-indiviso-ecuador.html' `
'{"@type":"Question","name":"¿Puedo ganar por prescripción la parte de mis copropietarios?","acceptedAnswer":{"@type":"Answer","text":"Es muy difícil entre copropietarios porque la ley presume que se posee a nombre de todos. Necesitas demostrar posesión exclusiva de toda la cosa. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si compré la parte de un copropietario puedo prescribir la del otro?","acceptedAnswer":{"@type":"Answer","text":"Si posees exclusivamente toda la propiedad sin reconocer al otro copropietario, el plazo puede correr. Pero la prueba es exigente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si quiero regularizar un terreno en sucesión indivisa?","acceptedAnswer":{"@type":"Answer","text":"En sucesión indivisa lo correcto es tramitar la partición. La prescripción entre coherederos es excepcional y difícil de probar. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Un copropietario que nunca apareció puede prescribir contra mí?","acceptedAnswer":{"@type":"Answer","text":"Si ese copropietario demostró posesión exclusiva mientras tú no aparecías, sí puede intentar la prescripción. Por eso es importante mantenerse presente. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo ganar por prescripción la parte de mis copropietarios?</summary><p class="faq-answer">Es muy difícil entre copropietarios porque la ley presume que se posee a nombre de todos. Necesitas demostrar posesión exclusiva de toda la cosa. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si compré la parte de un copropietario puedo prescribir la del otro?</summary><p class="faq-answer">Si posees exclusivamente toda la propiedad sin reconocer al otro copropietario, el plazo puede correr. Pero la prueba es exigente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si quiero regularizar un terreno en sucesión indivisa?</summary><p class="faq-answer">En sucesión indivisa lo correcto es tramitar la partición. La prescripción entre coherederos es excepcional y difícil de probar. Escríbenos: 0994859814.</p></details>
<details><summary>¿Un copropietario que nunca apareció puede prescribir contra mí?</summary><p class="faq-answer">Si ese copropietario demostró posesión exclusiva mientras tú no aparecías, sí puede intentar la prescripción. Por eso es importante mantenerse presente. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'prescripcion-adquisitiva-herencia-ecuador.html' `
'{"@type":"Question","name":"¿Puedo sumar el tiempo de posesión de mi padre fallecido al mío?","acceptedAnswer":{"@type":"Answer","text":"Sí, mediante la acumulación de posesiones. Debes probar que hubo una transmisión de posesión directa de tu padre a ti. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si mis hermanos se oponen a que prescriba el terreno heredado?","acceptedAnswer":{"@type":"Answer","text":"Ellos pueden impugnar el proceso. Si hubo posesión compartida, el juicio se complica. Si solo tú has poseído, tienes argumentos más sólidos. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La partición de herencia es más rápida que la prescripción?","acceptedAnswer":{"@type":"Answer","text":"En general sí. Si hay acuerdo entre herederos, la partición notarial puede cerrarse en semanas. La prescripción puede tomar años. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Sin posesión efectiva tramitada puedo igual iniciar la prescripción?","acceptedAnswer":{"@type":"Answer","text":"Sí. La posesión efectiva no es requisito previo para la prescripción adquisitiva. Son trámites independientes. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo sumar el tiempo de posesión de mi padre fallecido al mío?</summary><p class="faq-answer">Sí, mediante la acumulación de posesiones. Debes probar que hubo una transmisión de posesión directa de tu padre a ti. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si mis hermanos se oponen a que prescriba el terreno heredado?</summary><p class="faq-answer">Ellos pueden impugnar el proceso. Si hubo posesión compartida, el juicio se complica. Si solo tú has poseído, tienes argumentos más sólidos. Escríbenos: 0994859814.</p></details>
<details><summary>¿La partición de herencia es más rápida que la prescripción?</summary><p class="faq-answer">En general sí. Si hay acuerdo entre herederos, la partición notarial puede cerrarse en semanas. La prescripción puede tomar años. Escríbenos: 0994859814.</p></details>
<details><summary>¿Sin posesión efectiva tramitada puedo igual iniciar la prescripción?</summary><p class="faq-answer">Sí. La posesión efectiva no es requisito previo para la prescripción adquisitiva. Son trámites independientes. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'prescripcion-extraordinaria-sin-titulo-ecuador.html' `
'{"@type":"Question","name":"¿Cuál es la diferencia entre prescripción ordinaria y extraordinaria?","acceptedAnswer":{"@type":"Answer","text":"La ordinaria requiere justo título y buena fe, y se completa en 5 años. La extraordinaria no requiere título pero exige 15 años de posesión real y continua. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La prescripción extraordinaria aplica también en ciudades?","acceptedAnswer":{"@type":"Answer","text":"Sí. Aplica en todo tipo de inmuebles — urbanos y rurales. Los requisitos son los mismos aunque las pruebas disponibles pueden variar. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si el terreno tiene dueño registrado pero nunca lo visitó?","acceptedAnswer":{"@type":"Answer","text":"Que el dueño nunca haya visitado facilita tu caso — demuestra que tú eras el único que lo usaba. Pero no sustituye la prueba de tu posesión. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo iniciar el juicio antes de completar los 15 años?","acceptedAnswer":{"@type":"Answer","text":"No. El plazo debe estar completo al momento de presentar la demanda. Iniciarlo antes es una causal de rechazo de la acción. Escríbenos: 0994859814."}}' `
'<details><summary>¿Cuál es la diferencia entre prescripción ordinaria y extraordinaria?</summary><p class="faq-answer">La ordinaria requiere justo título y buena fe, y se completa en 5 años. La extraordinaria no requiere título pero exige 15 años de posesión real y continua. Escríbenos: 0994859814.</p></details>
<details><summary>¿La prescripción extraordinaria aplica también en ciudades?</summary><p class="faq-answer">Sí. Aplica en todo tipo de inmuebles — urbanos y rurales. Los requisitos son los mismos aunque las pruebas disponibles pueden variar. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si el terreno tiene dueño registrado pero nunca lo visitó?</summary><p class="faq-answer">Que el dueño nunca haya visitado facilita tu caso — demuestra que tú eras el único que lo usaba. Pero no sustituye la prueba de tu posesión. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo iniciar el juicio antes de completar los 15 años?</summary><p class="faq-answer">No. El plazo debe estar completo al momento de presentar la demanda. Iniciarlo antes es una causal de rechazo de la acción. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'prescripcion-ordinaria-justo-titulo-ecuador.html' `
'{"@type":"Question","name":"¿Qué documentos califican como justo título en Ecuador?","acceptedAnswer":{"@type":"Answer","text":"Un contrato de compraventa válido, una promesa de compraventa cumplida, una cesión de derechos o una herencia que te puso en posesión del bien, entre otros. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si el justo título tiene un defecto formal puede igual servir?","acceptedAnswer":{"@type":"Answer","text":"Depende del defecto. Algunos defectos formales no destruyen el justo título si la causa de la adquisición fue válida. Eso debe evaluarse caso a caso. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La buena fe desaparece si el vendedor me advirtió que había problemas?","acceptedAnswer":{"@type":"Answer","text":"Sí. Si sabías de la existencia de un vicio al momento de adquirir, difícilmente puedes invocar buena fe ante el juez. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuándo exactamente empieza a correr el plazo de 5 años?","acceptedAnswer":{"@type":"Answer","text":"Desde que adquiriste la posesión con justo título y buena fe. No desde la firma del contrato sino desde que tomaste posesión real del inmueble. Escríbenos: 0994859814."}}' `
'<details><summary>¿Qué documentos califican como justo título en Ecuador?</summary><p class="faq-answer">Un contrato de compraventa válido, una promesa de compraventa cumplida, una cesión de derechos o una herencia que te puso en posesión del bien, entre otros. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si el justo título tiene un defecto formal puede igual servir?</summary><p class="faq-answer">Depende del defecto. Algunos defectos formales no destruyen el justo título si la causa de la adquisición fue válida. Eso debe evaluarse caso a caso. Escríbenos: 0994859814.</p></details>
<details><summary>¿La buena fe desaparece si el vendedor me advirtió que había problemas?</summary><p class="faq-answer">Sí. Si sabías de la existencia de un vicio al momento de adquirir, difícilmente puedes invocar buena fe ante el juez. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuándo exactamente empieza a correr el plazo de 5 años?</summary><p class="faq-answer">Desde que adquiriste la posesión con justo título y buena fe. No desde la firma del contrato sino desde que tomaste posesión real del inmueble. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'prescripcion-ordinaria-vs-extraordinaria-ecuador.html' `
'{"@type":"Question","name":"¿Es mejor siempre ir por la extraordinaria para evitar discusiones sobre el título?","acceptedAnswer":{"@type":"Answer","text":"En muchos casos sí, aunque el plazo sea más largo. Evitas el debate sobre la validez del título y te enfocas en probar la posesión. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuál tiene más probabilidades de éxito?","acceptedAnswer":{"@type":"Answer","text":"Depende del caso. Si tienes un buen título, la ordinaria es más rápida. Sin título, la extraordinaria es la única opción, pero bien preparada tiene altas probabilidades. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo cambiar de ordinaria a extraordinaria durante el juicio?","acceptedAnswer":{"@type":"Answer","text":"En general no. La acción debe determinarse bien desde la demanda. Un cambio posterior requiere modificar la demanda en etapas tempranas. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Los 5 años de la ordinaria empiezan desde cuándo exactamente?","acceptedAnswer":{"@type":"Answer","text":"Desde que adquiriste la posesión con justo título y buena fe. No desde la firma del contrato sino desde que tomaste posesión real del inmueble. Escríbenos: 0994859814."}}' `
'<details><summary>¿Es mejor siempre ir por la extraordinaria para evitar discusiones sobre el título?</summary><p class="faq-answer">En muchos casos sí, aunque el plazo sea más largo. Evitas el debate sobre la validez del título y te enfocas en probar la posesión. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuál tiene más probabilidades de éxito?</summary><p class="faq-answer">Depende del caso. Si tienes un buen título, la ordinaria es más rápida. Sin título, la extraordinaria es la única opción, pero bien preparada tiene altas probabilidades. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo cambiar de ordinaria a extraordinaria durante el juicio?</summary><p class="faq-answer">En general no. La acción debe determinarse bien desde la demanda. Un cambio posterior requiere modificar la demanda en etapas tempranas. Escríbenos: 0994859814.</p></details>
<details><summary>¿Los 5 años de la ordinaria empiezan desde cuándo exactamente?</summary><p class="faq-answer">Desde que adquiriste la posesión con justo título y buena fe. No desde la firma del contrato sino desde que tomaste posesión real del inmueble. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'que-alarga-juicio-prescripcion-ecuador.html' `
'{"@type":"Question","name":"¿Los feriados judiciales alargan el proceso?","acceptedAnswer":{"@type":"Answer","text":"Sí, especialmente los períodos de agosto y enero. Si el proceso cae en esas fechas, las notificaciones y audiencias se retrasan automáticamente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cambiar de abogado en mitad del proceso alarga el juicio?","acceptedAnswer":{"@type":"Answer","text":"Sí, normalmente. El nuevo abogado necesita tiempo para familiarizarse con el expediente y puede haber plazos que se pierden durante la transición. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuál es el factor que más puedo controlar para que sea más rápido?","acceptedAnswer":{"@type":"Answer","text":"Tener todos los documentos listos desde el inicio y responder en los plazos del proceso sin demoras. Eso elimina las esperas más evitables. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo hacer algo para evitar que el propietario aparezca y alargue el juicio?","acceptedAnswer":{"@type":"Answer","text":"No puedes impedir que aparezca — es su derecho. Pero tener un caso sólido desde el inicio reduce el impacto de su oposición sobre el resultado final. Escríbenos: 0994859814."}}' `
'<details><summary>¿Los feriados judiciales alargan el proceso?</summary><p class="faq-answer">Sí, especialmente los períodos de agosto y enero. Si el proceso cae en esas fechas, las notificaciones y audiencias se retrasan automáticamente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cambiar de abogado en mitad del proceso alarga el juicio?</summary><p class="faq-answer">Sí, normalmente. El nuevo abogado necesita tiempo para familiarizarse con el expediente y puede haber plazos que se pierden durante la transición. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuál es el factor que más puedo controlar para que sea más rápido?</summary><p class="faq-answer">Tener todos los documentos listos desde el inicio y responder en los plazos del proceso sin demoras. Eso elimina las esperas más evitables. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo hacer algo para evitar que el propietario aparezca y alargue el juicio?</summary><p class="faq-answer">No puedes impedir que aparezca — es su derecho. Pero tener un caso sólido desde el inicio reduce el impacto de su oposición sobre el resultado final. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'reconocimiento-dominio-ajeno-ecuador.html' `
'{"@type":"Question","name":"¿Si firmo una escritura de arrendamiento sobre el terreno que poseo, pierdo la prescripción?","acceptedAnswer":{"@type":"Answer","text":"Sí. Firmar como arrendatario implica reconocer al arrendador como propietario, lo que destruye el ánimo de dueño. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Un reconocimiento verbal ante testigos interrumpe la prescripción?","acceptedAnswer":{"@type":"Answer","text":"Puede. Si los testigos declaran en juicio que reconociste el dominio ajeno, ese reconocimiento tiene valor aunque no esté escrito. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si firmé antes un reconocimiento puedo igual ganar por prescripción?","acceptedAnswer":{"@type":"Answer","text":"Depende de cuándo fue y si seguiste la posesión con ánimo de dueño después. El plazo se reiniciaría desde ese momento. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Pedir prórroga al propietario para desalojar equivale a reconocer dominio?","acceptedAnswer":{"@type":"Answer","text":"Puede interpretarse así. Pedir tiempo para salir reconoce implícitamente que el terreno es de otro. Es un acto que puede usarse en tu contra. Escríbenos: 0994859814."}}' `
'<details><summary>¿Si firmo una escritura de arrendamiento sobre el terreno que poseo, pierdo la prescripción?</summary><p class="faq-answer">Sí. Firmar como arrendatario implica reconocer al arrendador como propietario, lo que destruye el ánimo de dueño. Escríbenos: 0994859814.</p></details>
<details><summary>¿Un reconocimiento verbal ante testigos interrumpe la prescripción?</summary><p class="faq-answer">Puede. Si los testigos declaran en juicio que reconociste el dominio ajeno, ese reconocimiento tiene valor aunque no esté escrito. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si firmé antes un reconocimiento puedo igual ganar por prescripción?</summary><p class="faq-answer">Depende de cuándo fue y si seguiste la posesión con ánimo de dueño después. El plazo se reiniciaría desde ese momento. Escríbenos: 0994859814.</p></details>
<details><summary>¿Pedir prórroga al propietario para desalojar equivale a reconocer dominio?</summary><p class="faq-answer">Puede interpretarse así. Pedir tiempo para salir reconoce implícitamente que el terreno es de otro. Es un acto que puede usarse en tu contra. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'regla-obligatoria-singularizacion-inmueble-prescripcion-reivindicacion.html' `
'{"@type":"Question","name":"¿Qué pasa si no identifico correctamente el inmueble en la demanda?","acceptedAnswer":{"@type":"Answer","text":"El juez puede rechazar la acción por ese defecto formal, aunque tengas razón en el fondo. La singularización correcta es un requisito de admisibilidad. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cómo se singulariza un terreno sin escritura?","acceptedAnswer":{"@type":"Answer","text":"Con coordenadas GPS, linderos descritos detalladamente, referencia a predios colindantes y en algunos casos un perito que certifique las dimensiones y ubicación exacta. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El número de catastro es suficiente para identificar el inmueble?","acceptedAnswer":{"@type":"Answer","text":"El número de catastro ayuda mucho. Pero la Corte exige una descripción que permita distinguir el inmueble de todos los demás — solo el número puede no ser suficiente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las reglas de singularización son las mismas en todo Ecuador?","acceptedAnswer":{"@type":"Answer","text":"Los criterios de la Corte Nacional son vinculantes en todo el país. Pero algunos jueces locales aplican estándares más o menos exigentes. Escríbenos: 0994859814."}}' `
'<details><summary>¿Qué pasa si no identifico correctamente el inmueble en la demanda?</summary><p class="faq-answer">El juez puede rechazar la acción por ese defecto formal, aunque tengas razón en el fondo. La singularización correcta es un requisito de admisibilidad. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cómo se singulariza un terreno sin escritura?</summary><p class="faq-answer">Con coordenadas GPS, linderos descritos detalladamente, referencia a predios colindantes y en algunos casos un perito que certifique las dimensiones y ubicación exacta. Escríbenos: 0994859814.</p></details>
<details><summary>¿El número de catastro es suficiente para identificar el inmueble?</summary><p class="faq-answer">El número de catastro ayuda mucho. Pero la Corte exige una descripción que permita distinguir el inmueble de todos los demás — solo el número puede no ser suficiente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las reglas de singularización son las mismas en todo Ecuador?</summary><p class="faq-answer">Los criterios de la Corte Nacional son vinculantes en todo el país. Pero algunos jueces locales aplican estándares más o menos exigentes. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'reivindicacion-terreno-requisitos-dominio-posesion-singularizacion.html' `
'{"@type":"Question","name":"¿Qué tipo de título necesito para la acción reivindicatoria?","acceptedAnswer":{"@type":"Answer","text":"Necesitas un título inscrito en el Registro de la Propiedad. Una escritura pública inscrita es lo más sólido. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si demando a quien posee pero el ocupante real es otro?","acceptedAnswer":{"@type":"Answer","text":"Si demandas al poseedor equivocado, el juicio puede perderse por ese motivo. Debes identificar correctamente quién ejerce la posesión material. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo pedir medidas cautelares mientras dura la acción reivindicatoria?","acceptedAnswer":{"@type":"Answer","text":"Sí. Puedes pedir la prohibición de enajenar el bien o la anotación de la demanda en el Registro para proteger tu posición. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La acción reivindicatoria tiene plazo de prescripción?","acceptedAnswer":{"@type":"Answer","text":"La acción en sí no prescribe mientras el propietario tenga el título. Pero si el poseedor completa la prescripción adquisitiva, la acción ya no procede. Escríbenos: 0994859814."}}' `
'<details><summary>¿Qué tipo de título necesito para la acción reivindicatoria?</summary><p class="faq-answer">Necesitas un título inscrito en el Registro de la Propiedad. Una escritura pública inscrita es lo más sólido. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si demando a quien posee pero el ocupante real es otro?</summary><p class="faq-answer">Si demandas al poseedor equivocado, el juicio puede perderse por ese motivo. Debes identificar correctamente quién ejerce la posesión material. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo pedir medidas cautelares mientras dura la acción reivindicatoria?</summary><p class="faq-answer">Sí. Puedes pedir la prohibición de enajenar el bien o la anotación de la demanda en el Registro para proteger tu posición. Escríbenos: 0994859814.</p></details>
<details><summary>¿La acción reivindicatoria tiene plazo de prescripción?</summary><p class="faq-answer">La acción en sí no prescribe mientras el propietario tenga el título. Pero si el poseedor completa la prescripción adquisitiva, la acción ya no procede. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'requisitos-prescripcion-adquisitiva-ecuador.html' `
'{"@type":"Question","name":"¿Qué pasa si cumplo 3 de los 4 requisitos pero fallo en uno?","acceptedAnswer":{"@type":"Answer","text":"El juicio no prospera. Los cuatro requisitos deben cumplirse simultáneamente durante todo el período de posesión. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El juez puede declarar la prescripción aunque el propietario no lo sepa?","acceptedAnswer":{"@type":"Answer","text":"Sí. Si fue notificado correctamente y no apareció, el juez puede declarar la prescripción en su rebeldía. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Los 4 requisitos deben cumplirse desde el primer día?","acceptedAnswer":{"@type":"Answer","text":"Deben cumplirse de forma continua durante todo el período. No basta con cumplirlos al inicio — cada uno debe mantenerse durante los 15 años completos. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo probar los 4 requisitos con los mismos documentos?","acceptedAnswer":{"@type":"Answer","text":"En parte sí. El pago del predial puede demostrar ánimo de dueño y publicidad al mismo tiempo. Lo ideal es tener pruebas específicas para cada requisito. Escríbenos: 0994859814."}}' `
'<details><summary>¿Qué pasa si cumplo 3 de los 4 requisitos pero fallo en uno?</summary><p class="faq-answer">El juicio no prospera. Los cuatro requisitos deben cumplirse simultáneamente durante todo el período de posesión. Escríbenos: 0994859814.</p></details>
<details><summary>¿El juez puede declarar la prescripción aunque el propietario no lo sepa?</summary><p class="faq-answer">Sí. Si fue notificado correctamente y no apareció, el juez puede declarar la prescripción en su rebeldía. Escríbenos: 0994859814.</p></details>
<details><summary>¿Los 4 requisitos deben cumplirse desde el primer día?</summary><p class="faq-answer">Deben cumplirse de forma continua durante todo el período. No basta con cumplirlos al inicio — cada uno debe mantenerse durante los 15 años completos. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo probar los 4 requisitos con los mismos documentos?</summary><p class="faq-answer">En parte sí. El pago del predial puede demostrar ánimo de dueño y publicidad al mismo tiempo. Lo ideal es tener pruebas específicas para cada requisito. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'sentencia-prescripcion-registro-propiedad-ecuador.html' `
'{"@type":"Question","name":"¿Qué documentos necesito para inscribir la sentencia en el Registro?","acceptedAnswer":{"@type":"Answer","text":"La sentencia ejecutoriada, el auto de ejecución del juez y una escritura pública de protocolización de la sentencia ante notario. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuánto cuesta inscribir la sentencia?","acceptedAnswer":{"@type":"Answer","text":"Depende del avalúo del terreno. Los aranceles del Registro varían por valor del bien, más costos notariales de protocolización. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo habitar el terreno mientras tramito la inscripción?","acceptedAnswer":{"@type":"Answer","text":"Si ya ganaste el juicio y la sentencia está ejecutoriada, sí. La inscripción es un paso adicional para tener el título formal pero no te impide estar en el terreno. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El Registro puede negar la inscripción de la sentencia?","acceptedAnswer":{"@type":"Answer","text":"Puede observarla si hay problemas formales o conflictos con inscripciones previas. El abogado debe anticipar esos posibles obstáculos antes de presentar. Escríbenos: 0994859814."}}' `
'<details><summary>¿Qué documentos necesito para inscribir la sentencia en el Registro?</summary><p class="faq-answer">La sentencia ejecutoriada, el auto de ejecución del juez y una escritura pública de protocolización de la sentencia ante notario. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuánto cuesta inscribir la sentencia?</summary><p class="faq-answer">Depende del avalúo del terreno. Los aranceles del Registro varían por valor del bien, más costos notariales de protocolización. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo habitar el terreno mientras tramito la inscripción?</summary><p class="faq-answer">Si ya ganaste el juicio y la sentencia está ejecutoriada, sí. La inscripción es un paso adicional para tener el título formal pero no te impide estar en el terreno. Escríbenos: 0994859814.</p></details>
<details><summary>¿El Registro puede negar la inscripción de la sentencia?</summary><p class="faq-answer">Puede observarla si hay problemas formales o conflictos con inscripciones previas. El abogado debe anticipar esos posibles obstáculos antes de presentar. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'terreno-abandonado-recuperar-ecuador.html' `
'{"@type":"Question","name":"¿Si el terreno está abandonado y nadie lo ocupa puedo prescribir igualmente?","acceptedAnswer":{"@type":"Answer","text":"No. Necesitas estar en posesión real del terreno. La prescripción la gana quien posee, no quien simplemente quiere el terreno. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El propietario que dejó el terreno abandonado puede recuperarlo cuando quiera?","acceptedAnswer":{"@type":"Answer","text":"Sí, mientras no haya prescripción adquisitiva completada. Pero si alguien lo poseyó por muchos años, puede ser tarde. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuánto tiempo de abandono hace que el terreno sea prescriptible?","acceptedAnswer":{"@type":"Answer","text":"El terreno no se vuelve prescriptible por el abandono solo. Quien lo ocupa necesita poseer efectiva y continuamente durante 15 años para prescribir. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si regreso al terreno que abandoné y el ocupante me impide entrar, qué hago?","acceptedAnswer":{"@type":"Answer","text":"Puedes intentar recuperar la posesión en el primer año. Si el ocupante lleva más tiempo, necesitas ir a la acción reivindicatoria. Escríbenos: 0994859814."}}' `
'<details><summary>¿Si el terreno está abandonado y nadie lo ocupa puedo prescribir igualmente?</summary><p class="faq-answer">No. Necesitas estar en posesión real del terreno. La prescripción la gana quien posee, no quien simplemente quiere el terreno. Escríbenos: 0994859814.</p></details>
<details><summary>¿El propietario que dejó el terreno abandonado puede recuperarlo cuando quiera?</summary><p class="faq-answer">Sí, mientras no haya prescripción adquisitiva completada. Pero si alguien lo poseyó por muchos años, puede ser tarde. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuánto tiempo de abandono hace que el terreno sea prescriptible?</summary><p class="faq-answer">El terreno no se vuelve prescriptible por el abandono solo. Quien lo ocupa necesita poseer efectiva y continuamente durante 15 años para prescribir. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si regreso al terreno que abandoné y el ocupante me impide entrar, qué hago?</summary><p class="faq-answer">Puedes intentar recuperar la posesión en el primer año. Si el ocupante lleva más tiempo, necesitas ir a la acción reivindicatoria. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'terreno-en-disputa-hermanos-prescripcion-ecuador.html' `
'{"@type":"Question","name":"¿Si vivía solo en el terreno familiar pero pagué a mis hermanos su parte, puedo prescribir?","acceptedAnswer":{"@type":"Answer","text":"Si los pagaste reconociendo su parte, eso puede interpretarse como copropiedad, no posesión exclusiva. Consulta antes de actuar. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Mis hermanos pueden demandarme mientras tramito la prescripción?","acceptedAnswer":{"@type":"Answer","text":"Sí. Pueden iniciar acciones civiles para impugnar el proceso o reclamar sus derechos como coherederos. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La partición judicial es mejor que la prescripción entre hermanos?","acceptedAnswer":{"@type":"Answer","text":"En muchos casos sí. Es más predecible y evita el estándar tan exigente de la prescripción entre copropietarios. Si hay acuerdo, la partición notarial es lo más rápido. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si uno de mis hermanos murió y sus hijos no aparecen, puedo prescribir su parte?","acceptedAnswer":{"@type":"Answer","text":"Es posible si se cumplen los requisitos de posesión exclusiva sobre esa parte. Pero el proceso involucra notificar a herederos desconocidos, lo que lo complica. Escríbenos: 0994859814."}}' `
'<details><summary>¿Si vivía solo en el terreno familiar pero pagué a mis hermanos su parte, puedo prescribir?</summary><p class="faq-answer">Si los pagaste reconociendo su parte, eso puede interpretarse como copropiedad, no posesión exclusiva. Consulta antes de actuar. Escríbenos: 0994859814.</p></details>
<details><summary>¿Mis hermanos pueden demandarme mientras tramito la prescripción?</summary><p class="faq-answer">Sí. Pueden iniciar acciones civiles para impugnar el proceso o reclamar sus derechos como coherederos. Escríbenos: 0994859814.</p></details>
<details><summary>¿La partición judicial es mejor que la prescripción entre hermanos?</summary><p class="faq-answer">En muchos casos sí. Es más predecible y evita el estándar tan exigente de la prescripción entre copropietarios. Si hay acuerdo, la partición notarial es lo más rápido. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si uno de mis hermanos murió y sus hijos no aparecen, puedo prescribir su parte?</summary><p class="faq-answer">Es posible si se cumplen los requisitos de posesión exclusiva sobre esa parte. Pero el proceso involucra notificar a herederos desconocidos, lo que lo complica. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'terreno-ocupado-escritura-ecuador.html' `
'{"@type":"Question","name":"¿Puedo sacar al ocupante antes de que cumplan los 15 años?","acceptedAnswer":{"@type":"Answer","text":"Sí. Mientras no se cumplan los 15 años puedes iniciar la acción reivindicatoria. Si ya los cumplieron, la situación es más complicada. Actúa cuanto antes. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Mi escritura sigue siendo válida aunque el ocupante lleve 15 años?","acceptedAnswer":{"@type":"Answer","text":"Sí, el título no desaparece. Pero el ocupante puede iniciar el juicio de prescripción y, si gana, el registro de tu escritura queda sin efecto sobre ese bien. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo vender el terreno aunque esté ocupado?","acceptedAnswer":{"@type":"Answer","text":"Legalmente puedes vender. Pero debes declararlo, y el comprador asume el riesgo del conflicto. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si el banco tiene hipoteca sobre ese terreno?","acceptedAnswer":{"@type":"Answer","text":"El banco mantiene su hipoteca independientemente del conflicto de posesión. Si el ocupante gana la prescripción, el problema con la hipoteca se complica. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo sacar al ocupante antes de que cumplan los 15 años?</summary><p class="faq-answer">Sí. Mientras no se cumplan los 15 años puedes iniciar la acción reivindicatoria. Si ya los cumplieron, la situación es más complicada. Actúa cuanto antes. Escríbenos: 0994859814.</p></details>
<details><summary>¿Mi escritura sigue siendo válida aunque el ocupante lleve 15 años?</summary><p class="faq-answer">Sí, el título no desaparece. Pero el ocupante puede iniciar el juicio de prescripción y, si gana, el registro de tu escritura queda sin efecto sobre ese bien. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo vender el terreno aunque esté ocupado?</summary><p class="faq-answer">Legalmente puedes vender. Pero debes declararlo, y el comprador asume el riesgo del conflicto. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si el banco tiene hipoteca sobre ese terreno?</summary><p class="faq-answer">El banco mantiene su hipoteca independientemente del conflicto de posesión. Si el ocupante gana la prescripción, el problema con la hipoteca se complica. Escríbenos: 0994859814.</p></details>'

Write-Host "`n=== DONE === Updated=$($updated) | Skipped=$($skipped) | NotFound=$($notFound)"
