$blogDir = 'c:\Users\HOLA\OneDrive\Escritorio\juristam-web\blog'
$utf8noBOM = New-Object System.Text.UTF8Encoding $false
$updated = 0; $skipped = 0; $notFound = 0

function Find-ArrayClose($str, $startPos) {
    $openPos = $str.IndexOf('[', $startPos)
    if ($openPos -lt 0) { return -1 }
    $depth = 0; $inStr = $false; $esc = $false
    $bsc = [int][char]92; $dqc = [int][char]34
    for ($i = $openPos; $i -lt $str.Length; $i++) {
        $ci = [int][char]$str[$i]
        if ($esc) { $esc = $false; continue }
        if ($ci -eq $bsc -and $inStr) { $esc = $true; continue }
        if ($ci -eq $dqc) { $inStr = !$inStr; continue }
        if (-not $inStr) {
            if ($str[$i] -eq '[') { $depth++ }
            elseif ($str[$i] -eq ']') { $depth--; if ($depth -eq 0) { return $i } }
        }
    }
    return -1
}

function Add-FaqData($filename, $jsonAdd, $htmlAdd) {
    $path = Join-Path $blogDir $filename
    if (-not (Test-Path $path)) { $script:notFound++; Write-Host "NOT FOUND: $filename"; return }
    $c = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
    $marker = $jsonAdd.Substring(0,[Math]::Min(50,$jsonAdd.Length))
    if ($c.IndexOf($marker) -ge 0) { $script:skipped++; Write-Host "SKIP: $filename"; return }
    $tag = '<script type="application/ld+json">'
    $si = $c.IndexOf($tag); $ei = $c.IndexOf('</script>', $si)
    if ($si -ge 0) {
        $jb = $c.Substring($si+$tag.Length, $ei-$si-$tag.Length)
        $fp = $jb.IndexOf('"FAQPage"')
        if ($fp -ge 0) {
            $mp = $jb.IndexOf('"mainEntity"', $fp)
            $cl = Find-ArrayClose $jb $mp
            if ($cl -ge 0) {
                $abs = $si+$tag.Length+$cl
                $c = $c.Substring(0,$abs) + ',' + $jsonAdd + $c.Substring($abs)
            }
        }
    }
    $ld = $c.LastIndexOf('</details>')
    if ($ld -ge 0) {
        $cd = $c.IndexOf('</div>', $ld+10)
        if ($cd -ge 0) { $c = $c.Substring(0,$cd) + $htmlAdd + "`n" + $c.Substring($cd) }
    }
    [System.IO.File]::WriteAllText($path, $c, $utf8noBOM)
    $script:updated++; Write-Host "OK: $filename"
}

Add-FaqData '15-anos-como-se-cuentan-prescripcion-ecuador.html' `
'{"@type":"Question","name":"¿Los 15 años corren aunque no viva en el terreno?","acceptedAnswer":{"@type":"Answer","text":"No necesariamente. Si delegaste el cuidado y sigues ejerciendo actos de dueño, el tiempo puede seguir corriendo. Si lo abandonaste completamente, puede interrumpirse. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si el terreno estuvo a nombre de otra persona todo ese tiempo?","acceptedAnswer":{"@type":"Answer","text":"Que otro tenga el título no impide la prescripción. Lo que cuenta es quién ejerció posesión real, no quién aparece en el registro. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuánto tarda el juicio una vez que completo los 15 años?","acceptedAnswer":{"@type":"Answer","text":"Entre 1 y 3 años dependiendo del juzgado y si hay oposición. No es automático — necesitas un proceso judicial para que el juez declare la prescripción. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Una carta notarial interrumpe los 15 años?","acceptedAnswer":{"@type":"Answer","text":"No. Solo la demanda judicial presentada y notificada correctamente interrumpe el plazo. Una carta notarial no tiene ese efecto legal en Ecuador. Escríbenos: 0994859814."}}' `
'<details><summary>¿Los 15 años corren aunque no viva en el terreno?</summary><p class="faq-answer">No necesariamente. Si delegaste el cuidado y sigues ejerciendo actos de dueño, el tiempo puede seguir corriendo. Si lo abandonaste completamente, puede interrumpirse. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si el terreno estuvo a nombre de otra persona todo ese tiempo?</summary><p class="faq-answer">Que otro tenga el título no impide la prescripción. Lo que cuenta es quién ejerció posesión real, no quién aparece en el registro. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuánto tarda el juicio una vez que completo los 15 años?</summary><p class="faq-answer">Entre 1 y 3 años dependiendo del juzgado y si hay oposición. No es automático — necesitas un proceso judicial para que el juez declare la prescripción. Escríbenos: 0994859814.</p></details>
<details><summary>¿Una carta notarial interrumpe los 15 años?</summary><p class="faq-answer">No. Solo la demanda judicial presentada y notificada correctamente interrumpe el plazo. Una carta notarial no tiene ese efecto legal en Ecuador. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'accion-reivindicatoria-terreno-ecuador.html' `
'{"@type":"Question","name":"¿Puedo iniciar la acción reivindicatoria sin escritura pública?","acceptedAnswer":{"@type":"Answer","text":"No. Exige que el demandante sea el propietario con título inscrito. Sin escritura, la acción correcta sería otra. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si el ocupante lleva más de 15 años en el terreno?","acceptedAnswer":{"@type":"Answer","text":"Puede oponer la prescripción adquisitiva y ganar aunque tú tengas escritura. Por eso actuar a tiempo es crítico. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuánto tarda una acción reivindicatoria en Ecuador?","acceptedAnswer":{"@type":"Answer","text":"Entre 1 y 2 años en promedio, dependiendo de si el ocupante opone excepciones y del juzgado. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Sirve contra un familiar que ocupa el terreno?","acceptedAnswer":{"@type":"Answer","text":"Sí procede legalmente, pero entre familiares puede haber reconocimiento implícito de dominio que complica el caso. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo iniciar la acción reivindicatoria sin escritura pública?</summary><p class="faq-answer">No. Exige que el demandante sea el propietario con título inscrito. Sin escritura, la acción correcta sería otra. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si el ocupante lleva más de 15 años en el terreno?</summary><p class="faq-answer">Puede oponer la prescripción adquisitiva y ganar aunque tú tengas escritura. Por eso actuar a tiempo es crítico. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuánto tarda una acción reivindicatoria en Ecuador?</summary><p class="faq-answer">Entre 1 y 2 años en promedio, dependiendo de si el ocupante opone excepciones y del juzgado. Escríbenos: 0994859814.</p></details>
<details><summary>¿Sirve contra un familiar que ocupa el terreno?</summary><p class="faq-answer">Sí procede legalmente, pero entre familiares puede haber reconocimiento implícito de dominio que complica el caso. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'animo-de-dueno-posesion-ecuador.html' `
'{"@type":"Question","name":"¿Pagar el impuesto predial demuestra ánimo de dueño?","acceptedAnswer":{"@type":"Answer","text":"Sí, es una de las pruebas más sólidas. El pago sistemático del predial a tu nombre demuestra que te comportas como propietario ante el Estado. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Arrendar el terreno a terceros demuestra ánimo de dueño?","acceptedAnswer":{"@type":"Answer","text":"Sí. Cobrar arriendo es un acto típico de propietario y tiene mucho peso como prueba ante el juez. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El ánimo de dueño se destruye si alguna vez reconocí que el terreno era de otro?","acceptedAnswer":{"@type":"Answer","text":"Sí. Ese reconocimiento puede destruirlo y reiniciar el plazo de prescripción. Es uno de los errores más graves. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Construir en el terreno sin permiso demuestra ánimo de dueño?","acceptedAnswer":{"@type":"Answer","text":"Sí. Levantar construcciones es un acto de dominio concreto y visible que los jueces valoran mucho. Escríbenos: 0994859814."}}' `
'<details><summary>¿Pagar el impuesto predial demuestra ánimo de dueño?</summary><p class="faq-answer">Sí, es una de las pruebas más sólidas. El pago sistemático del predial a tu nombre demuestra que te comportas como propietario ante el Estado. Escríbenos: 0994859814.</p></details>
<details><summary>¿Arrendar el terreno a terceros demuestra ánimo de dueño?</summary><p class="faq-answer">Sí. Cobrar arriendo es un acto típico de propietario y tiene mucho peso como prueba ante el juez. Escríbenos: 0994859814.</p></details>
<details><summary>¿El ánimo de dueño se destruye si alguna vez reconocí que el terreno era de otro?</summary><p class="faq-answer">Sí. Ese reconocimiento puede destruirlo y reiniciar el plazo de prescripción. Es uno de los errores más graves. Escríbenos: 0994859814.</p></details>
<details><summary>¿Construir en el terreno sin permiso demuestra ánimo de dueño?</summary><p class="faq-answer">Sí. Levantar construcciones es un acto de dominio concreto y visible que los jueces valoran mucho. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'ausencia-de-titulo-afecta-posesion-ecuador.html' `
'{"@type":"Question","name":"¿Puedo ganar la prescripción aunque nunca tuve ningún documento del terreno?","acceptedAnswer":{"@type":"Answer","text":"Sí, mediante la prescripción extraordinaria. No necesitas título — necesitas probar 15 años de posesión real, pública, pacífica y continua. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Un contrato de compraventa sin escritura sirve como justo título?","acceptedAnswer":{"@type":"Answer","text":"Puede servir como justo título para la prescripción ordinaria si fue válido en su momento, aunque no esté escriturado. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pruebas compensan la falta de escritura?","acceptedAnswer":{"@type":"Answer","text":"Pago de prediales, facturas de servicios, fotografías antiguas, testimonios de vecinos e informes periciales. Juntos pueden construir un caso sólido. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La falta de título afecta más en zona rural?","acceptedAnswer":{"@type":"Answer","text":"No cambia los requisitos de fondo. En zona rural los testigos y el peritaje tienen aún más peso. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo ganar la prescripción aunque nunca tuve ningún documento del terreno?</summary><p class="faq-answer">Sí, mediante la prescripción extraordinaria. No necesitas título — necesitas probar 15 años de posesión real, pública, pacífica y continua. Escríbenos: 0994859814.</p></details>
<details><summary>¿Un contrato de compraventa sin escritura sirve como justo título?</summary><p class="faq-answer">Puede servir como justo título para la prescripción ordinaria si fue válido en su momento, aunque no esté escriturado. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pruebas compensan la falta de escritura?</summary><p class="faq-answer">Pago de prediales, facturas de servicios, fotografías antiguas, testimonios de vecinos e informes periciales. Juntos pueden construir un caso sólido. Escríbenos: 0994859814.</p></details>
<details><summary>¿La falta de título afecta más en zona rural?</summary><p class="faq-answer">No cambia los requisitos de fondo. En zona rural los testigos y el peritaje tienen aún más peso. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'calcular-anos-ocupante-terreno-ecuador.html' `
'{"@type":"Question","name":"¿Cómo sé desde cuándo exactamente empezó a poseer el ocupante?","acceptedAnswer":{"@type":"Answer","text":"Con testimonios de vecinos, fotos antiguas, facturas de servicios a nombre del ocupante o peritos que estimen la antigüedad de construcciones. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si el ocupante entró hace menos de 10 años tengo tiempo de actuar?","acceptedAnswer":{"@type":"Answer","text":"Sí, y mientras menos años lleva es más fácil interrumpir el plazo. La acción más efectiva es la demanda judicial. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si lleva exactamente 15 años puedo aún recuperar el terreno?","acceptedAnswer":{"@type":"Answer","text":"Solo si puedes probar que el plazo fue interrumpido en algún momento. Sin interrupción, ya podría oponer la prescripción. Consulta urgente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El tiempo de un familiar anterior del ocupante cuenta para los 15 años?","acceptedAnswer":{"@type":"Answer","text":"Puede sumar si hubo transferencia de posesión entre ellos — accesión de posesiones. El juez lo evalúa caso a caso. Escríbenos: 0994859814."}}' `
'<details><summary>¿Cómo sé desde cuándo exactamente empezó a poseer el ocupante?</summary><p class="faq-answer">Con testimonios de vecinos, fotos antiguas, facturas de servicios a nombre del ocupante o peritos que estimen la antigüedad de construcciones. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si el ocupante entró hace menos de 10 años tengo tiempo de actuar?</summary><p class="faq-answer">Sí, y mientras menos años lleva es más fácil interrumpir el plazo. La acción más efectiva es la demanda judicial. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si lleva exactamente 15 años puedo aún recuperar el terreno?</summary><p class="faq-answer">Solo si puedes probar que el plazo fue interrumpido en algún momento. Sin interrupción, ya podría oponer la prescripción. Consulta urgente. Escríbenos: 0994859814.</p></details>
<details><summary>¿El tiempo de un familiar anterior del ocupante cuenta para los 15 años?</summary><p class="faq-answer">Puede sumar si hubo transferencia de posesión entre ellos — accesión de posesiones. El juez lo evalúa caso a caso. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'carta-notarial-interrumpe-prescripcion-ecuador.html' `
'{"@type":"Question","name":"¿Qué sí interrumpe la prescripción adquisitiva en Ecuador?","acceptedAnswer":{"@type":"Answer","text":"Solo la presentación de una demanda judicial ante el juez competente, con la respectiva notificación al poseedor. Una carta notarial no tiene ese efecto. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo interrumpirla con una mediación?","acceptedAnswer":{"@type":"Answer","text":"No. La mediación no interrumpe la prescripción adquisitiva porque no es un acto judicial con efecto interruptivo reconocido en la ley. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si el poseedor me firma un documento reconociendo que el terreno es mío, ayuda?","acceptedAnswer":{"@type":"Answer","text":"Ese reconocimiento destruye el ánimo de dueño y puede interrumpir la prescripción. Debe estar bien documentado, preferiblemente ante notario. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuánto tiempo tengo para demandar antes de que prescriba?","acceptedAnswer":{"@type":"Answer","text":"Si el poseedor lleva menos de 15 años, aún estás a tiempo. Actuar antes de que se cumplan es fundamental. Escríbenos: 0994859814."}}' `
'<details><summary>¿Qué sí interrumpe la prescripción adquisitiva en Ecuador?</summary><p class="faq-answer">Solo la presentación de una demanda judicial ante el juez competente, con la respectiva notificación al poseedor. Una carta notarial no tiene ese efecto. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo interrumpirla con una mediación?</summary><p class="faq-answer">No. La mediación no interrumpe la prescripción adquisitiva porque no es un acto judicial con efecto interruptivo reconocido en la ley. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si el poseedor me firma un documento reconociendo que el terreno es mío, ayuda?</summary><p class="faq-answer">Ese reconocimiento destruye el ánimo de dueño y puede interrumpir la prescripción. Debe estar bien documentado, preferiblemente ante notario. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuánto tiempo tengo para demandar antes de que prescriba?</summary><p class="faq-answer">Si el poseedor lleva menos de 15 años, aún estás a tiempo. Actuar antes de que se cumplan es fundamental. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'como-probar-posesion-terreno-ecuador.html' `
'{"@type":"Question","name":"¿Cuántos testigos necesito para probar la posesión?","acceptedAnswer":{"@type":"Answer","text":"La ley no fija un número mínimo, pero en la práctica se presentan entre 2 y 4. Lo que importa es la calidad del testimonio, no la cantidad. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Sirven fotos de Google Maps como prueba de posesión?","acceptedAnswer":{"@type":"Answer","text":"Como prueba complementaria sí. Las capturas de Google Street View con fecha pueden mostrar estructuras en el terreno a lo largo del tiempo. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El certificado del municipio sirve como prueba?","acceptedAnswer":{"@type":"Answer","text":"Sí. Permisos municipales, catastros y pago de tasas municipales a tu nombre son documentos con mucho valor probatorio. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si mis pruebas son de menos de 15 años?","acceptedAnswer":{"@type":"Answer","text":"Puedes sumar la posesión de tu causante si te la transfirió directamente. Un perito puede complementar pruebas escasas. Escríbenos: 0994859814."}}' `
'<details><summary>¿Cuántos testigos necesito para probar la posesión?</summary><p class="faq-answer">La ley no fija un número mínimo, pero en la práctica se presentan entre 2 y 4. Lo que importa es la calidad del testimonio, no la cantidad. Escríbenos: 0994859814.</p></details>
<details><summary>¿Sirven fotos de Google Maps como prueba de posesión?</summary><p class="faq-answer">Como prueba complementaria sí. Las capturas de Google Street View con fecha pueden mostrar estructuras en el terreno a lo largo del tiempo. Escríbenos: 0994859814.</p></details>
<details><summary>¿El certificado del municipio sirve como prueba?</summary><p class="faq-answer">Sí. Permisos municipales, catastros y pago de tasas municipales a tu nombre son documentos con mucho valor probatorio. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si mis pruebas son de menos de 15 años?</summary><p class="faq-answer">Puedes sumar la posesión de tu causante si te la transfirió directamente. Un perito puede complementar pruebas escasas. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'construcciones-arboles-prueba-posesion-ecuador.html' `
'{"@type":"Question","name":"¿El perito puede determinar la antigüedad exacta de un árbol?","acceptedAnswer":{"@type":"Answer","text":"Sí. Mediante técnicas dendrológicas puede estimar con bastante precisión la antigüedad de árboles plantados, lo que constituye prueba directa de posesión. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si el propietario demuele las construcciones antes del juicio?","acceptedAnswer":{"@type":"Answer","text":"La demolición posterior no borra la prueba si hay fotos, testimonios o informes periciales anteriores que documenten la existencia de esas construcciones. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Una casa construida sin permiso municipal sirve como prueba?","acceptedAnswer":{"@type":"Answer","text":"Sí. La ausencia de permiso no elimina el valor probatorio. Un perito puede certificar su existencia y antigüedad independientemente del permiso. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Los cultivos sirven igual que las construcciones?","acceptedAnswer":{"@type":"Answer","text":"Sí y a veces mejor, porque las plantaciones tienen una antigüedad más fácil de estimar pericialmente y son señal inequívoca de aprovechamiento del terreno. Escríbenos: 0994859814."}}' `
'<details><summary>¿El perito puede determinar la antigüedad exacta de un árbol?</summary><p class="faq-answer">Sí. Mediante técnicas dendrológicas puede estimar con bastante precisión la antigüedad de árboles plantados, lo que constituye prueba directa de posesión. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si el propietario demuele las construcciones antes del juicio?</summary><p class="faq-answer">La demolición posterior no borra la prueba si hay fotos, testimonios o informes periciales anteriores que documenten la existencia de esas construcciones. Escríbenos: 0994859814.</p></details>
<details><summary>¿Una casa construida sin permiso municipal sirve como prueba?</summary><p class="faq-answer">Sí. La ausencia de permiso no elimina el valor probatorio. Un perito puede certificar su existencia y antigüedad independientemente del permiso. Escríbenos: 0994859814.</p></details>
<details><summary>¿Los cultivos sirven igual que las construcciones?</summary><p class="faq-answer">Sí y a veces mejor, porque las plantaciones tienen una antigüedad más fácil de estimar pericialmente y son señal inequívoca de aprovechamiento del terreno. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'costo-juicio-prescripcion-adquisitiva-ecuador.html' `
'{"@type":"Question","name":"¿Hay que pagar al principio o al final del juicio?","acceptedAnswer":{"@type":"Answer","text":"Lo usual es un anticipo al inicio y el saldo al avanzar el proceso. Los costos judiciales se pagan desde el primer día. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El juicio es más barato si no hay oposición?","acceptedAnswer":{"@type":"Answer","text":"Sí. Si el propietario no aparece o no contesta, el proceso es más corto y por lo tanto menos costoso en honorarios. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si pierdo el juicio, pierdo todo lo invertido?","acceptedAnswer":{"@type":"Answer","text":"Los honorarios pagados no se devuelven. Por eso es importante hacer un análisis serio del caso antes de iniciar. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El peritaje tiene costo aparte del honorario del abogado?","acceptedAnswer":{"@type":"Answer","text":"Generalmente sí. El peritaje es un costo adicional que varía según la extensión y ubicación del terreno. Escríbenos: 0994859814."}}' `
'<details><summary>¿Hay que pagar al principio o al final del juicio?</summary><p class="faq-answer">Lo usual es un anticipo al inicio y el saldo al avanzar el proceso. Los costos judiciales se pagan desde el primer día. Escríbenos: 0994859814.</p></details>
<details><summary>¿El juicio es más barato si no hay oposición?</summary><p class="faq-answer">Sí. Si el propietario no aparece o no contesta, el proceso es más corto y por lo tanto menos costoso en honorarios. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si pierdo el juicio, pierdo todo lo invertido?</summary><p class="faq-answer">Los honorarios pagados no se devuelven. Por eso es importante hacer un análisis serio del caso antes de iniciar. Escríbenos: 0994859814.</p></details>
<details><summary>¿El peritaje tiene costo aparte del honorario del abogado?</summary><p class="faq-answer">Generalmente sí. El peritaje es un costo adicional que varía según la extensión y ubicación del terreno. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'cuanto-tarda-juicio-prescripcion-adquisitiva-ecuador.html' `
'{"@type":"Question","name":"¿Hay forma de acelerar el proceso?","acceptedAnswer":{"@type":"Answer","text":"Tener toda la documentación lista desde el inicio y responder en los plazos del proceso reduce los tiempos significativamente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué etapa es la que más tiempo toma?","acceptedAnswer":{"@type":"Answer","text":"La etapa probatoria — especialmente si hay peritaje — y la espera de la sentencia son las más lentas. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo vender el terreno mientras dura el juicio?","acceptedAnswer":{"@type":"Answer","text":"No puedes inscribir la transferencia porque aún no eres el titular registrado. Después de la sentencia favorable sí podrás vender. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si el propietario muere durante el juicio, qué pasa?","acceptedAnswer":{"@type":"Answer","text":"El juicio continúa contra sus herederos. El proceso no se detiene por ese motivo. Escríbenos: 0994859814."}}' `
'<details><summary>¿Hay forma de acelerar el proceso?</summary><p class="faq-answer">Tener toda la documentación lista desde el inicio y responder en los plazos del proceso reduce los tiempos significativamente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué etapa es la que más tiempo toma?</summary><p class="faq-answer">La etapa probatoria — especialmente si hay peritaje — y la espera de la sentencia son las más lentas. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo vender el terreno mientras dura el juicio?</summary><p class="faq-answer">No puedes inscribir la transferencia porque aún no eres el titular registrado. Después de la sentencia favorable sí podrás vender. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si el propietario muere durante el juicio, qué pasa?</summary><p class="faq-answer">El juicio continúa contra sus herederos. El proceso no se detiene por ese motivo. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'demanda-judicial-interrumpe-prescripcion-ecuador.html' `
'{"@type":"Question","name":"¿Desde qué momento exacto se interrumpe la prescripción?","acceptedAnswer":{"@type":"Answer","text":"Desde la notificación válida al poseedor. No basta con presentar la demanda — debe ser notificada correctamente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si la demanda fue rechazada o archivada, igual interrumpió el plazo?","acceptedAnswer":{"@type":"Answer","text":"No. Una demanda rechazada o nunca notificada válidamente no produce efecto interruptivo. El plazo sigue corriendo. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Después de interrumpir, desde cuándo vuelve a contar el plazo?","acceptedAnswer":{"@type":"Answer","text":"Desde cero, desde el momento de la interrupción. Si el poseedor sigue en el terreno, empieza un nuevo plazo de 15 años. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo interrumpir aunque no vaya a ganar el juicio inmediatamente?","acceptedAnswer":{"@type":"Answer","text":"Sí. Interrumpir el plazo es un objetivo válido aunque el juicio tome tiempo. Detener el reloj protege tu posición. Escríbenos: 0994859814."}}' `
'<details><summary>¿Desde qué momento exacto se interrumpe la prescripción?</summary><p class="faq-answer">Desde la notificación válida al poseedor. No basta con presentar la demanda — debe ser notificada correctamente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si la demanda fue rechazada o archivada, igual interrumpió el plazo?</summary><p class="faq-answer">No. Una demanda rechazada o nunca notificada válidamente no produce efecto interruptivo. El plazo sigue corriendo. Escríbenos: 0994859814.</p></details>
<details><summary>¿Después de interrumpir, desde cuándo vuelve a contar el plazo?</summary><p class="faq-answer">Desde cero, desde el momento de la interrupción. Si el poseedor sigue en el terreno, empieza un nuevo plazo de 15 años. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo interrumpir aunque no vaya a ganar el juicio inmediatamente?</summary><p class="faq-answer">Sí. Interrumpir el plazo es un objetivo válido aunque el juicio tome tiempo. Detener el reloj protege tu posición. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'desalojo-terreno-ecuador.html' `
'{"@type":"Question","name":"¿Cuál es la diferencia entre desalojo y acción reivindicatoria?","acceptedAnswer":{"@type":"Answer","text":"El desalojo es más rápido pero solo aplica en casos de arrendamiento o precario reciente. La reivindicatoria es más amplia pero más lenta. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo pedir el desalojo si el ocupante lleva 5 años?","acceptedAnswer":{"@type":"Answer","text":"Depende de cómo ingresó. Si fue como precario sin contrato, podría proceder. Si lleva años en posesión real, la reivindicatoria puede ser más adecuada. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuánto tarda un juicio de desalojo en Ecuador?","acceptedAnswer":{"@type":"Answer","text":"Un desalojo por vía verbal sumaria puede resolverse en 2 a 6 meses si el caso es claro. Con apelaciones puede extenderse más. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo desalojar al ocupante mientras dura el juicio?","acceptedAnswer":{"@type":"Answer","text":"No. No puedes tomar medidas de hecho. Debes esperar la resolución del juez o solicitar medidas cautelares dentro del proceso. Escríbenos: 0994859814."}}' `
'<details><summary>¿Cuál es la diferencia entre desalojo y acción reivindicatoria?</summary><p class="faq-answer">El desalojo es más rápido pero solo aplica en casos de arrendamiento o precario reciente. La reivindicatoria es más amplia pero más lenta. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo pedir el desalojo si el ocupante lleva 5 años?</summary><p class="faq-answer">Depende de cómo ingresó. Si fue como precario sin contrato, podría proceder. Si lleva años en posesión real, la reivindicatoria puede ser más adecuada. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuánto tarda un juicio de desalojo en Ecuador?</summary><p class="faq-answer">Un desalojo por vía verbal sumaria puede resolverse en 2 a 6 meses si el caso es claro. Con apelaciones puede extenderse más. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo desalojar al ocupante mientras dura el juicio?</summary><p class="faq-answer">No. No puedes tomar medidas de hecho. Debes esperar la resolución del juez o solicitar medidas cautelares dentro del proceso. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'documentos-probar-posesion-terreno-sin-escritura-ecuador.html' `
'{"@type":"Question","name":"¿El contrato de compraventa sin notarizar sirve como prueba?","acceptedAnswer":{"@type":"Answer","text":"Como indicio sí, pero su valor es limitado. Combinado con facturas de servicios y testimonios refuerza la prueba general. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las fotos en redes sociales con ubicación sirven?","acceptedAnswer":{"@type":"Answer","text":"Pueden servir como prueba complementaria si muestran al poseedor en el terreno con fechas verificables. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Un testamento donde me dejaron el terreno sin escritura ayuda?","acceptedAnswer":{"@type":"Answer","text":"Sí. Acredita que hubo transmisión de posesión aunque no haya escritura, y puede sumarse a tu tiempo para completar los 15 años. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Las facturas de construcción o materiales sirven?","acceptedAnswer":{"@type":"Answer","text":"Sí, especialmente si están a tu nombre y tienen la dirección del terreno. Demuestran que invertiste recursos en ese inmueble. Escríbenos: 0994859814."}}' `
'<details><summary>¿El contrato de compraventa sin notarizar sirve como prueba?</summary><p class="faq-answer">Como indicio sí, pero su valor es limitado. Combinado con facturas de servicios y testimonios refuerza la prueba general. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las fotos en redes sociales con ubicación sirven?</summary><p class="faq-answer">Pueden servir como prueba complementaria si muestran al poseedor en el terreno con fechas verificables. Escríbenos: 0994859814.</p></details>
<details><summary>¿Un testamento donde me dejaron el terreno sin escritura ayuda?</summary><p class="faq-answer">Sí. Acredita que hubo transmisión de posesión aunque no haya escritura, y puede sumarse a tu tiempo para completar los 15 años. Escríbenos: 0994859814.</p></details>
<details><summary>¿Las facturas de construcción o materiales sirven?</summary><p class="faq-answer">Sí, especialmente si están a tu nombre y tienen la dirección del terreno. Demuestran que invertiste recursos en ese inmueble. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'errores-evitar-poseyendo-sin-escritura-ecuador.html' `
'{"@type":"Question","name":"¿Es un error pagar arriendo aunque sea mínimo al supuesto dueño?","acceptedAnswer":{"@type":"Answer","text":"Sí, es uno de los errores más graves. Pagar arriendo es reconocer que eres arrendatario, no propietario, y destruye completamente el ánimo de dueño. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Pedir permiso para construir en el terreno afecta la prescripción?","acceptedAnswer":{"@type":"Answer","text":"Si pides permiso al propietario original, estás reconociendo su dominio. Eso puede interrumpir la prescripción o destruir el ánimo de dueño. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Dejar el terreno vacío por temporadas destruye la posesión?","acceptedAnswer":{"@type":"Answer","text":"Depende del tiempo. Una ausencia de semanas no destruye la posesión. Una de meses o años sin mantener el terreno sí puede ser problemática. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Firmar cualquier documento relacionado al terreno puede ser un error?","acceptedAnswer":{"@type":"Answer","text":"Sí. Antes de firmar cualquier cosa relacionada al terreno consulta con un abogado. Puede destruir tu posición en minutos. Escríbenos: 0994859814."}}' `
'<details><summary>¿Es un error pagar arriendo aunque sea mínimo al supuesto dueño?</summary><p class="faq-answer">Sí, es uno de los errores más graves. Pagar arriendo es reconocer que eres arrendatario, no propietario, y destruye completamente el ánimo de dueño. Escríbenos: 0994859814.</p></details>
<details><summary>¿Pedir permiso para construir en el terreno afecta la prescripción?</summary><p class="faq-answer">Si pides permiso al propietario original, estás reconociendo su dominio. Eso puede interrumpir la prescripción o destruir el ánimo de dueño. Escríbenos: 0994859814.</p></details>
<details><summary>¿Dejar el terreno vacío por temporadas destruye la posesión?</summary><p class="faq-answer">Depende del tiempo. Una ausencia de semanas no destruye la posesión. Una de meses o años sin mantener el terreno sí puede ser problemática. Escríbenos: 0994859814.</p></details>
<details><summary>¿Firmar cualquier documento relacionado al terreno puede ser un error?</summary><p class="faq-answer">Sí. Antes de firmar cualquier cosa relacionada al terreno consulta con un abogado. Puede destruir tu posición en minutos. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'etapas-juicio-prescripcion-adquisitiva-ecuador.html' `
'{"@type":"Question","name":"¿Qué pasa si no aparece el propietario durante el juicio?","acceptedAnswer":{"@type":"Answer","text":"Si después de las notificaciones legales no comparece, se lo declara en rebeldía y el proceso continúa. Debes probar igual tu posesión. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo apelar si pierdo en primera instancia?","acceptedAnswer":{"@type":"Answer","text":"Sí. Tienes derecho a apelar ante la Corte Provincial si hay errores en la sentencia de primera instancia. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué hace el juez en la inspección judicial del terreno?","acceptedAnswer":{"@type":"Answer","text":"Verifica in situ que el poseedor efectivamente está en el terreno, evalúa las mejoras y construcciones y recoge evidencia directa. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuánto tiempo hay entre la sentencia y la inscripción en el Registro?","acceptedAnswer":{"@type":"Answer","text":"Generalmente entre 30 y 60 días para ejecutar la sentencia e inscribirla. El abogado debe gestionar esos trámites activamente. Escríbenos: 0994859814."}}' `
'<details><summary>¿Qué pasa si no aparece el propietario durante el juicio?</summary><p class="faq-answer">Si después de las notificaciones legales no comparece, se lo declara en rebeldía y el proceso continúa. Debes probar igual tu posesión. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo apelar si pierdo en primera instancia?</summary><p class="faq-answer">Sí. Tienes derecho a apelar ante la Corte Provincial si hay errores en la sentencia de primera instancia. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué hace el juez en la inspección judicial del terreno?</summary><p class="faq-answer">Verifica in situ que el poseedor efectivamente está en el terreno, evalúa las mejoras y construcciones y recoge evidencia directa. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuánto tiempo hay entre la sentencia y la inscripción en el Registro?</summary><p class="faq-answer">Generalmente entre 30 y 60 días para ejecutar la sentencia e inscribirla. El abogado debe gestionar esos trámites activamente. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'fotos-facturas-servicios-prueba-posesion-ecuador.html' `
'{"@type":"Question","name":"¿Las facturas de agua y luz son suficientes por sí solas?","acceptedAnswer":{"@type":"Answer","text":"No. Son prueba importante pero deben combinarse con otros elementos: testimonios, peritaje o documentos municipales. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cómo presento las fotos ante el juez para que sean válidas?","acceptedAnswer":{"@type":"Answer","text":"Deben adjuntarse al proceso con certificación de autenticidad. Las fotos con metadatos de fecha y ubicación tienen más valor. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si las facturas están a nombre de un familiar y no mío?","acceptedAnswer":{"@type":"Answer","text":"Si ese familiar también poseyó y te transfirió la posesión, su tiempo puede sumarse al tuyo. Debe acreditarse esa transferencia. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Documentos del IESS o del SRI sirven como prueba de posesión?","acceptedAnswer":{"@type":"Answer","text":"Si declaran esa dirección como tu domicilio o lugar de actividad económica, sí pueden servir como indicios complementarios. Escríbenos: 0994859814."}}' `
'<details><summary>¿Las facturas de agua y luz son suficientes por sí solas?</summary><p class="faq-answer">No. Son prueba importante pero deben combinarse con otros elementos: testimonios, peritaje o documentos municipales. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cómo presento las fotos ante el juez para que sean válidas?</summary><p class="faq-answer">Deben adjuntarse al proceso con certificación de autenticidad. Las fotos con metadatos de fecha y ubicación tienen más valor. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si las facturas están a nombre de un familiar y no mío?</summary><p class="faq-answer">Si ese familiar también poseyó y te transfirió la posesión, su tiempo puede sumarse al tuyo. Debe acreditarse esa transferencia. Escríbenos: 0994859814.</p></details>
<details><summary>¿Documentos del IESS o del SRI sirven como prueba de posesión?</summary><p class="faq-answer">Si declaran esa dirección como tu domicilio o lugar de actividad económica, sí pueden servir como indicios complementarios. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'herencia-terreno-sin-escritura-ecuador.html' `
'{"@type":"Question","name":"¿Puedo sumar el tiempo de posesión de mis abuelos también?","acceptedAnswer":{"@type":"Answer","text":"Sí, si hay una cadena continua de transmisión de posesión — de abuelos a padres y de padres a ti. Cada transmisión debe acreditarse. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿La posesión efectiva me da derecho a iniciar el juicio de prescripción?","acceptedAnswer":{"@type":"Answer","text":"La posesión efectiva no regulariza el terreno pero te posiciona como sucesor de la posesión del causante para efectos del juicio. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué pasa si hay varios herederos y solo yo he poseído el terreno?","acceptedAnswer":{"@type":"Answer","text":"Puedes iniciar el juicio solo. Pero los otros herederos también tienen intereses, lo que puede complicar el proceso. Consulta antes. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El terreno heredado en zona rural tiene las mismas reglas?","acceptedAnswer":{"@type":"Answer","text":"Los requisitos de fondo son los mismos. En zona rural los testigos y el perito tienen aún más peso. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo sumar el tiempo de posesión de mis abuelos también?</summary><p class="faq-answer">Sí, si hay una cadena continua de transmisión de posesión — de abuelos a padres y de padres a ti. Cada transmisión debe acreditarse. Escríbenos: 0994859814.</p></details>
<details><summary>¿La posesión efectiva me da derecho a iniciar el juicio de prescripción?</summary><p class="faq-answer">La posesión efectiva no regulariza el terreno pero te posiciona como sucesor de la posesión del causante para efectos del juicio. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué pasa si hay varios herederos y solo yo he poseído el terreno?</summary><p class="faq-answer">Puedes iniciar el juicio solo. Pero los otros herederos también tienen intereses, lo que puede complicar el proceso. Consulta antes. Escríbenos: 0994859814.</p></details>
<details><summary>¿El terreno heredado en zona rural tiene las mismas reglas?</summary><p class="faq-answer">Los requisitos de fondo son los mismos. En zona rural los testigos y el perito tienen aún más peso. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'interrumpir-prescripcion-adquisitiva-ecuador.html' `
'{"@type":"Question","name":"¿Puedo interrumpirla con una denuncia penal?","acceptedAnswer":{"@type":"Answer","text":"Una denuncia penal sola no interrumpe la prescripción adquisitiva. Necesitas una acción civil específica ante el juez competente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Después de interrumpir, el poseedor pierde todo el tiempo acumulado?","acceptedAnswer":{"@type":"Answer","text":"Sí. La interrupción borra el tiempo acumulado. Si continúa la posesión después, empieza un nuevo plazo de 15 años desde cero. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si interrumpo ahora y luego no hago nada, qué pasa?","acceptedAnswer":{"@type":"Answer","text":"El poseedor vuelve a acumular tiempo. La interrupción solo gana tiempo — no resuelve el problema de fondo. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puedo hacer la demanda de interrupción yo mismo sin abogado?","acceptedAnswer":{"@type":"Answer","text":"No. Los procesos judiciales en Ecuador requieren patrocinio de abogado. Intentarlo sin uno arriesga que la demanda no produzca el efecto interruptivo. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puedo interrumpirla con una denuncia penal?</summary><p class="faq-answer">Una denuncia penal sola no interrumpe la prescripción adquisitiva. Necesitas una acción civil específica ante el juez competente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Después de interrumpir, el poseedor pierde todo el tiempo acumulado?</summary><p class="faq-answer">Sí. La interrupción borra el tiempo acumulado. Si continúa la posesión después, empieza un nuevo plazo de 15 años desde cero. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si interrumpo ahora y luego no hago nada, qué pasa?</summary><p class="faq-answer">El poseedor vuelve a acumular tiempo. La interrupción solo gana tiempo — no resuelve el problema de fondo. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puedo hacer la demanda de interrupción yo mismo sin abogado?</summary><p class="faq-answer">No. Los procesos judiciales en Ecuador requieren patrocinio de abogado. Intentarlo sin uno arriesga que la demanda no produzca el efecto interruptivo. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'ocupante-familiar-terreno-ecuador.html' `
'{"@type":"Question","name":"¿Puede un familiar ganar mi terreno por prescripción?","acceptedAnswer":{"@type":"Answer","text":"Depende de cómo entró. Si entró con tu permiso reconociendo tu dominio, difícilmente puede prescribir. Si actuó como dueño sin reconocer tu autoridad, sí es posible. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Es mejor llegar a un acuerdo con el familiar o ir al juicio?","acceptedAnswer":{"@type":"Answer","text":"Siempre que sea posible, un acuerdo notarial es más rápido y menos costoso. Pero si el familiar ya tiene posesión avanzada, el acuerdo igual es urgente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Los familiares que viven como favor pueden prescribir?","acceptedAnswer":{"@type":"Answer","text":"No si quedó claro que fue un préstamo o autorización. El problema es cuando eso no quedó documentado y el tiempo pasa. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Qué documento protege mi terreno si dejo vivir a un familiar ahí?","acceptedAnswer":{"@type":"Answer","text":"Un comodato notarial o contrato de préstamo de uso. Ese documento prueba que el familiar reconoció tu dominio y no puede usarlo para prescribir. Escríbenos: 0994859814."}}' `
'<details><summary>¿Puede un familiar ganar mi terreno por prescripción?</summary><p class="faq-answer">Depende de cómo entró. Si entró con tu permiso reconociendo tu dominio, difícilmente puede prescribir. Si actuó como dueño sin reconocer tu autoridad, sí es posible. Escríbenos: 0994859814.</p></details>
<details><summary>¿Es mejor llegar a un acuerdo con el familiar o ir al juicio?</summary><p class="faq-answer">Siempre que sea posible, un acuerdo notarial es más rápido y menos costoso. Pero si el familiar ya tiene posesión avanzada, el acuerdo igual es urgente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Los familiares que viven como favor pueden prescribir?</summary><p class="faq-answer">No si quedó claro que fue un préstamo o autorización. El problema es cuando eso no quedó documentado y el tiempo pasa. Escríbenos: 0994859814.</p></details>
<details><summary>¿Qué documento protege mi terreno si dejo vivir a un familiar ahí?</summary><p class="faq-answer">Un comodato notarial o contrato de préstamo de uso. Ese documento prueba que el familiar reconoció tu dominio y no puede usarlo para prescribir. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'pago-predial-prueba-posesion-ecuador.html' `
'{"@type":"Question","name":"¿Si pago el predial a nombre de otro vale igual?","acceptedAnswer":{"@type":"Answer","text":"No. Para que sirva como prueba de tu posesión debe estar a tu nombre. Si está a nombre del propietario original, no te beneficia directamente. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Cuántos años de pago de predial necesito para que sirva como prueba?","acceptedAnswer":{"@type":"Answer","text":"No hay un mínimo legal. Pero mientras más años consecutivos tengas a tu nombre, más convincente es la prueba ante el juez. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Si el municipio no tiene registrado el predio puedo igual pagar el predial?","acceptedAnswer":{"@type":"Answer","text":"Puedes gestionar el registro catastral del predio a tu nombre — eso también es un acto de propietario. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El pago en efectivo sin comprobante vale?","acceptedAnswer":{"@type":"Answer","text":"Sin comprobante es muy difícil de probar. El recibo oficial del municipio es lo que vale como prueba. Escríbenos: 0994859814."}}' `
'<details><summary>¿Si pago el predial a nombre de otro vale igual?</summary><p class="faq-answer">No. Para que sirva como prueba de tu posesión debe estar a tu nombre. Si está a nombre del propietario original, no te beneficia directamente. Escríbenos: 0994859814.</p></details>
<details><summary>¿Cuántos años de pago de predial necesito para que sirva como prueba?</summary><p class="faq-answer">No hay un mínimo legal. Pero mientras más años consecutivos tengas a tu nombre, más convincente es la prueba ante el juez. Escríbenos: 0994859814.</p></details>
<details><summary>¿Si el municipio no tiene registrado el predio puedo igual pagar el predial?</summary><p class="faq-answer">Puedes gestionar el registro catastral del predio a tu nombre — eso también es un acto de propietario. Escríbenos: 0994859814.</p></details>
<details><summary>¿El pago en efectivo sin comprobante vale?</summary><p class="faq-answer">Sin comprobante es muy difícil de probar. El recibo oficial del municipio es lo que vale como prueba. Escríbenos: 0994859814.</p></details>'

Add-FaqData 'peritos-posesion-terreno-ecuador.html' `
'{"@type":"Question","name":"¿Quién paga el perito en el juicio?","acceptedAnswer":{"@type":"Answer","text":"La parte que lo solicita paga el peritaje. Si el juez lo ordena de oficio, el costo se distribuye. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿Puede el propietario objetar el informe pericial?","acceptedAnswer":{"@type":"Answer","text":"Sí. Puede presentar observaciones y solicitar un contraperitage. El juez valora ambos y decide cuál tiene más fundamento. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El perito puede estimar la fecha de construcción de una casa antigua?","acceptedAnswer":{"@type":"Answer","text":"Sí. A través de materiales, técnicas constructivas y estado de deterioro puede estimar con razonable precisión cuándo fue construida. Escríbenos: 0994859814."}},{"@type":"Question","name":"¿El informe pericial solo es suficiente para ganar?","acceptedAnswer":{"@type":"Answer","text":"No. Es la prueba más poderosa pero debe complementarse con testigos y documentos. Una sola prueba raramente es suficiente. Escríbenos: 0994859814."}}' `
'<details><summary>¿Quién paga el perito en el juicio?</summary><p class="faq-answer">La parte que lo solicita paga el peritaje. Si el juez lo ordena de oficio, el costo se distribuye. Escríbenos: 0994859814.</p></details>
<details><summary>¿Puede el propietario objetar el informe pericial?</summary><p class="faq-answer">Sí. Puede presentar observaciones y solicitar un contraperitage. El juez valora ambos y decide cuál tiene más fundamento. Escríbenos: 0994859814.</p></details>
<details><summary>¿El perito puede estimar la fecha de construcción de una casa antigua?</summary><p class="faq-answer">Sí. A través de materiales, técnicas constructivas y estado de deterioro puede estimar con razonable precisión cuándo fue construida. Escríbenos: 0994859814.</p></details>
<details><summary>¿El informe pericial solo es suficiente para ganar?</summary><p class="faq-answer">No. Es la prueba más poderosa pero debe complementarse con testigos y documentos. Una sola prueba raramente es suficiente. Escríbenos: 0994859814.</p></details>'

Write-Host "`n=== DONE === Updated=$($updated) | Skipped=$($skipped) | NotFound=$($notFound)"
