$blogDir = 'c:\Users\HOLA\OneDrive\Escritorio\juristam-web\blog'
$utf8noBOM = New-Object System.Text.UTF8Encoding $false
$updated = 0; $skipped = 0; $notFound = 0

function Update-Meta {
    param($f, $t, $d)
    $path = Join-Path $blogDir $f
    if (-not (Test-Path $path)) { Write-Host "NOT FOUND: $f"; $script:notFound++; return }
    $c = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
    $orig = $c

    # <title>
    $m = [regex]::Match($c, '<title>[^<]*</title>')
    if ($m.Success) { $c = $c.Replace($m.Value, '<title>' + $t + '</title>') }

    # meta name=description
    $m = [regex]::Match($c, '<meta\s+name="description"\s+content="[^"]*"[^>]*/?>')
    if (-not $m.Success) { $m = [regex]::Match($c, '<meta\s+content="[^"]*"\s+name="description"[^>]*/?>') }
    if ($m.Success) {
        $ov = [regex]::Match($m.Value, '(?<=content=")[^"]*').Value
        $c = $c.Replace($m.Value, $m.Value.Replace('content="' + $ov + '"', 'content="' + $d + '"'))
    }

    # og:title
    $m = [regex]::Match($c, '<meta\s+property="og:title"\s+content="[^"]*"[^>]*/?>')
    if (-not $m.Success) { $m = [regex]::Match($c, '<meta\s+content="[^"]*"\s+property="og:title"[^>]*/?>') }
    if ($m.Success) {
        $ov = [regex]::Match($m.Value, '(?<=content=")[^"]*').Value
        $c = $c.Replace($m.Value, $m.Value.Replace('content="' + $ov + '"', 'content="' + $t + '"'))
    }

    # og:description
    $m = [regex]::Match($c, '<meta\s+property="og:description"\s+content="[^"]*"[^>]*/?>')
    if (-not $m.Success) { $m = [regex]::Match($c, '<meta\s+content="[^"]*"\s+property="og:description"[^>]*/?>') }
    if ($m.Success) {
        $ov = [regex]::Match($m.Value, '(?<=content=")[^"]*').Value
        $c = $c.Replace($m.Value, $m.Value.Replace('content="' + $ov + '"', 'content="' + $d + '"'))
    }

    if ($c -ne $orig) {
        [System.IO.File]::WriteAllText($path, $c, $utf8noBOM)
        Write-Host "OK: $f"
        $script:updated++
    } else {
        Write-Host "NC: $f"
        $script:skipped++
    }
}

Update-Meta '15-anos-como-se-cuentan-prescripcion-ecuador.html' 'Como se cuentan los 15 anos de prescripcion adquisitiva' 'Los 15 años de prescripción adquisitiva empiezan desde que tomaste posesión real del terreno. Te explicamos cómo calcularlos y qué eventos pueden.'
Update-Meta 'abono-multa-transito-reinicia-prescripcion.html' 'Abono de multa de tránsito: ¿reinicia la prescripción?' 'Un pago parcial de una multa de tránsito puede reiniciar el plazo de prescripción desde cero en Ecuador.'
Update-Meta 'abordaje-embarcaciones-ecuador.html' 'Abordaje en Ecuador: quién responde y cómo reclamar' 'El abordaje entre embarcaciones en Ecuador genera responsabilidades según la culpa de cada capitán. Te explicamos la normativa aplicable, quién.'
Update-Meta 'abuso-mayoria-societaria-ecuador.html' 'Abuso de mayoría en empresas ecuatorianas: qué hacer' 'El abuso de mayoría ocurre cuando socios controladores toman decisiones que los benefician a ellos en Ecuador.'
Update-Meta 'accidente-en-puerto-ecuador-responsabilidad.html' 'Accidente en puerto ecuatoriano: quién responde' 'Los accidentes en puertos ecuatorianos pueden involucrar al operador portuario, la naviera o el importador.'
Update-Meta 'accidentes-contaminacion-maritima-ecuador.html' 'Accidentes y contaminación marítima en Ecuador' 'Los accidentes marítimos en Ecuador activan responsabilidades civiles y penales simultáneamente. Te explicamos quién responde, qué normas aplican y.'
Update-Meta 'accion-por-infraccion-marca-ecuador.html' 'Infracción de marca en Ecuador: cómo actuar' 'Si alguien usa tu marca sin autorización puedes actuar ante el SENADI. Te explicamos los pasos, los plazos y qué pruebas necesitas para ganar el caso.'
Update-Meta 'accion-reivindicatoria-terreno-ecuador.html' 'Acción reivindicatoria para recuperar tu terreno' 'La acción reivindicatoria permite recuperar tu terreno aunque alguien lo ocupe. Debes probar dominio, posesión del demandado e identificar el.'
Update-Meta 'adn-basta-paternidad-matrimonial-ecuador.html' 'El ADN negativo basta si el hijo nació en matrimonio' 'Si el hijo nació dentro del matrimonio en Ecuador el ADN negativo tiene más peso jurídico que en el reconocimiento voluntario.'
Update-Meta 'adn-negativo-impugnacion-paternidad-ecuador.html' 'ADN negativo en Ecuador: cómo dejar de pagar pensión' 'Si el ADN salió negativo y sigues pagando pensión en Ecuador, hay una ruta legal para dejar de hacerlo. El camino depende de cómo reconociste al niño.'
Update-Meta 'agente-vs-naviera-quien-responde-ecuador.html' 'Agente marítimo vs naviera: quién responde' 'Cuando hay un problema con tu embarque en Ecuador, la primera pregunta es si reclamar al agente marítimo o a la naviera.'
Update-Meta 'albacea-funciones-ecuador.html' 'El albacea en Ecuador: funciones y por qué nombrarlo' 'El albacea ejecuta el testamento y protege tus decisiones después de morir. Te explicamos qué puede hacer, qué límites tiene y por qué no nombrarlo.'
Update-Meta 'albacea-testamento-ecuador.html' 'El albacea en el testamento ecuatoriano' 'El albacea es la figura que más se ignora al redactar un testamento en Ecuador. Te explicamos qué hace exactamente, quién puede serlo y por qué.'
Update-Meta 'animo-de-dueno-posesion-ecuador.html' 'El animo de dueno en la posesion Ecuador: como demostra' 'El ánimo de dueño no es una actitud — son actos concretos visibles. Te explicamos qué conductas demuestran posesión con ánimo de dueño ante el juez.'
Update-Meta 'ant-online-consultar-multas-ecuador.html' 'Consultar multas de tránsito en el portal ANT' 'Consultar tus multas en el portal de la ANT es el primer paso antes de tramitar la prescripción. Te explicamos cómo hacerlo según la ciudad y qué.'
Update-Meta 'ant-vs-municipio-quien-resuelve-prescripcion-multa.html' 'ANT o municipio: quién resuelve tu prescripción' 'La entidad correcta depende de quién emitió la multa. Presentarla ante la equivocada resulta en rechazo aunque el plazo haya vencido.'
Update-Meta 'antecedentes-judiciales-ecuador.html' 'Antecedentes judiciales Ecuador: cómo ocultar tu nombre' 'Guía 2026 para ocultar tu nombre del SATJE y del SIAF de Fiscalía en Ecuador. Normativa, requisitos, costos y proceso paso a paso para eliminar tus.'
Update-Meta 'antecedentes-judiciales-trabajo-empleo-ecuador.html' 'Antecedentes judiciales y empleo en Ecuador' 'El SATJE visible puede cerrarte puertas laborales en Ecuador. Muchas empresas lo verifican antes de contratar.'
Update-Meta 'antecedentes-judiciales-visa-tramites-ecuador.html' 'Antecedentes judiciales y visa en Ecuador' 'Los antecedentes judiciales visibles pueden afectar tus solicitudes de visa. Te explicamos qué países verifican más y cómo proteger tu solicitud.'
Update-Meta 'antecedentes-transito-satje-ocultamiento.html' 'Antecedentes de tránsito en el SATJE: cómo ocultar' 'Si tienes un proceso de tránsito terminado visible en el SATJE, puedes solicitar su ocultamiento bajo condiciones específicas.'
Update-Meta 'apellido-padrastro-ecuador.html' 'Apellido del padrastro en Ecuador: las dos rutas' 'Poner el apellido del padrastro en Ecuador requiere adopción formal o proceso judicial. El Registro Civil no puede hacer el cambio directamente.'
Update-Meta 'archivo-fiscal-no-desaparece-que-hacer.html' 'El archivo fiscal no desaparece del SIAF: qué hacer' 'El archivo fiscal no limpia el SIAF automáticamente. Si tus datos siguen visibles aunque el caso está archivado, necesitas tramitar el ocultamiento.'
Update-Meta 'aseguradora-rechaza-siniestro-maritimo.html' 'La aseguradora rechazó el siniestro: qué hacer' 'Si la aseguradora rechazó tu siniestro marítimo en Ecuador ese rechazo puede revertirse. Te explicamos los motivos más frecuentes y cómo impugnar la.'
Update-Meta 'ausencia-de-titulo-afecta-posesion-ecuador.html' 'Sin escritura: ¿se debilita tu prueba de posesión?' 'Sin escritura puedes ganar por prescripción extraordinaria. Pero sí afecta cómo debes probar la posesión y qué tipo de prescripción invocar.'
Update-Meta 'averia-gruesa-maritima-ecuador.html' 'Avería gruesa en Ecuador: qué es y cómo actuar' 'La avería gruesa se declara cuando el capitán toma medidas extraordinarias para salvar el buque. Todos los interesados deben contribuir.'
Update-Meta 'banco-revisa-satje-credito-ecuador.html' 'El banco revisa el SATJE para dar créditos Ecuador' 'Los bancos consultan el SATJE antes de aprobar créditos en Ecuador. Un proceso visible aunque ya terminó puede afectar tu solicitud.'
Update-Meta 'bill-of-lading-conocimiento-embarque-ecuador.html' 'Bill of lading en Ecuador: tipos y valor jurídico' 'El bill of lading es el documento más importante en una operación marítima. Es contrato de transporte, recibo de carga y título de propiedad.'
Update-Meta 'bl-vs-sea-waybill-ecuador.html' 'BL vs Sea Waybill en Ecuador: cuál usar' 'El BL es negociable y el sea waybill no. Esa diferencia fundamental cambia quién puede reclamar y cómo.'
Update-Meta 'blindaje-patrimonial-legal-ecuador.html' 'Blindaje patrimonial legal para empresarios Ecuador' 'El blindaje patrimonial legal protege tus bienes personales de deudas y riesgos empresariales en Ecuador.'
Update-Meta 'bloqueo-decisiones-socios-ecuador.html' 'Empresa paralizada por socios: opciones legales' 'Cuando los socios no pueden tomar decisiones en Ecuador hay mecanismos legales para destrabar la empresa sin necesariamente disolverla.'
Update-Meta 'bonificacion-voluntaria-finiquito-despido-ecuador.html' 'Bonificación + finiquito: puede ser despido encubierto' 'Si firmaste un finiquito con bonificación sin causa legal ni desahucio, la Corte Nacional dice que puede ser despido intempestivo disfrazado.'
Update-Meta 'buro-credito-multa-transito-ecuador.html' 'Multas de tránsito y buró de crédito en Ecuador' 'Las multas de tránsito no afectan directamente el buró de crédito, pero el cobro coactivo sí puede hacerlo.'
Update-Meta 'busqueda-anterioridad-marca-ecuador.html' 'Búsqueda de anterioridad de marca en Ecuador' 'La búsqueda de anterioridad antes de registrar tu marca en Ecuador es el paso más importante. Te explicamos cómo hacerla, qué buscar y cómo.'
Update-Meta 'calcular-anos-ocupante-terreno-ecuador.html' 'Cómo calcular los años que lleva el ocupante' 'Calcular cuántos años lleva el ocupante define tu riesgo y la estrategia correcta. Te explicamos cómo determinar la fecha de inicio de posesión y qué.'
Update-Meta 'calcular-prescripcion-multa-transito-ecuador.html' '¿Tu multa de tránsito ya prescribió? Cómo calcularlo' 'Para calcular si tu multa prescribió necesitas la fecha de infracción, si hubo pagos y si hubo notificación judicial válida.'
Update-Meta 'cambiar-orden-apellidos-ecuador.html' 'Cambiar orden de apellidos en Ecuador: cómo hacerlo' 'Sí puedes cambiar el orden de los apellidos en Ecuador para que el materno sea primero. Hay vía notarial y judicial.'
Update-Meta 'cambio-apellido-ecuador-cedula-identidad.html' 'Quitar el apellido paterno en Ecuador: cuándo procede' 'Sí se puede quitar el apellido paterno en Ecuador. El proceso depende de si vas por vía notarial o judicial.'
Update-Meta 'cambio-apellido-menor-edad-ecuador.html' 'Cambio de apellido de un menor en Ecuador' 'Cambiar el apellido de un menor en Ecuador requiere autorización judicial. El interés superior del niño es el criterio central.'
Update-Meta 'cambio-apellido-via-judicial-ecuador.html' 'Cambio de apellido por vía judicial en Ecuador' 'La vía judicial para cambiar el apellido en Ecuador aplica cuando el Registro Civil rechaza la solicitud o no tienes los 10 años de uso que exige la.'
Update-Meta 'cancelacion-antecedentes-policia-judicial-ecuador.html' 'Cancelar antecedentes en la Policía Judicial Ecuador' 'La cancelación de antecedentes en la Policía Judicial es gratuita si cumpliste tu condena. Es diferente al SATJE y requiere un trámite separado.'
Update-Meta 'cancelacion-marca-no-uso-ecuador.html' 'Cancelar una marca por no uso en Ecuador' 'Si una marca está registrada pero no se usa puedes pedir su cancelación ante el SENADI. Y si atacan la tuya por esta vía, te explicamos cómo.'
Update-Meta 'carga-humeda-danada-contenedor-ecuador.html' 'Carga húmeda en contenedor Ecuador: qué hacer' 'Cuando la carga llega húmeda en Ecuador la causa del daño determina quién responde. Documentar el estado al recibirla es el paso más importante.'
Update-Meta 'carga-maritima-danos-averia-ecuador.html' 'Daños y averías en carga marítima en Ecuador' 'Los daños en carga marítima en Ecuador tienen plazos cortos para reclamar. El primer acto jurídico correcto puede determinar el resultado final.'
Update-Meta 'carga-prueba-tributaria-ecuador.html' 'Carga de la prueba tributaria: por qué puedes perder' 'En materia tributaria en Ecuador no basta tener razón: debes probarla. Este es el error que más casos hace perder frente al SRI.'
Update-Meta 'carta-notarial-interrumpe-prescripcion-ecuador.html' '¿Una carta notarial interrumpe la prescripción?' 'Una carta notarial no interrumpe la prescripción adquisitiva en Ecuador. Solo una demanda judicial tiene ese efecto.'
Update-Meta 'causas-legales-dejar-pagar-pension-alimenticia-ecuador.html' 'Causas legales para no pagar pensión en Ecuador' 'No puedes dejar de pagar pensión sin causa legal reconocida en Ecuador o podrías ir preso. Te explicamos cuáles son las causas válidas y cómo.'
Update-Meta 'cero-puntos-licencia-ecuador.html' 'Licencia con cero puntos en Ecuador: qué hacer' 'Con cero puntos no puedes manejar legalmente en Ecuador. Te explicamos si hay alguna excepción, cómo recuperar los puntos y cuánto tarda el proceso.'
Update-Meta 'certificado-antecedentes-penales-donde-sacar-ecuador.html' 'Dónde sacar el certificado de antecedentes Ecuador' 'El certificado de antecedentes penales lo emite la Policía Judicial. Es diferente al SATJE y al récord policial.'
Update-Meta 'charter-party-ecuador.html' 'Charter party en Ecuador: cláusulas y protección' 'El charter party es el contrato mediante el cual el armador pone el buque a disposición del fletador. Te explicamos los tipos, el laytime y cómo.'
Update-Meta 'cheque-protestado-satje-ocultamiento-ecuador.html' 'Cheque protestado en el SATJE Ecuador: cómo ocultar' 'Un juicio por cheque protestado visible en el SATJE puede ocultarse si ya terminó. Te explicamos las condiciones exactas, qué documentos necesitas y.'
Update-Meta 'cheque-sin-fondos-ecuador.html' 'Cheque sin fondos Ecuador: qué hacer antes de que venza' 'El cheque sin fondos activa dos acciones en Ecuador: penal y civil. Los plazos empiezan desde el protesto.'
Update-Meta 'cierre-sas-ecuador.html' 'Cierre de SAS en Ecuador: cómo disolver la empresa' 'Cerrar una SAS en Ecuador requiere un proceso formal de disolución y liquidación ante la Supercias. Te explicamos cada etapa, cuánto tarda y los.'
Update-Meta 'cinco-anos-prescripcion-multa-transito-ecuador.html' 'Los cinco años de prescripción de multas en Ecuador' 'Los cinco años de prescripción de multas de tránsito se cuentan desde la infracción, no desde que te enteraste.'
Update-Meta 'clases-niza-marca-ecuador.html' 'Clases de Niza para marcas en Ecuador: cuál elegir' 'Elegir la clase de Niza incorrecta puede dejarte desprotegido en Ecuador. Te explicamos cuáles son, cómo identificar la correcta y los errores más.'
Update-Meta 'clausulas-penales-contratos-ecuador.html' 'Cláusulas penales en contratos empresariales Ecuador' 'Las cláusulas penales en contratos empresariales protegen frente al incumplimiento en Ecuador. Te explicamos cuándo son exigibles, cómo se calculan y.'
Update-Meta 'coactiva-deuda-ilegal-defensa-ecuador.html' 'Deuda ilegal en coactiva Ecuador: cómo defenderte' 'No toda deuda en coactiva es legalmente válida en Ecuador. La Corte Nacional aclaró cuándo el título puede atacarse.'
Update-Meta 'coactiva-ex-representante-legal-nulidad-ecuador.html' 'Coactiva a ex representante legal: cuándo es ilegal' 'Cobrar una coactiva a quien ya no era representante legal puede ser ilegal en Ecuador. La Corte Nacional ha reconocido la nulidad en estos casos.'
Update-Meta 'coactiva-interrumpe-prescripcion-multa-transito.html' 'Cobro coactivo de multa: ¿interrumpe la prescripción?' 'Un cobro coactivo válido puede interrumpir la prescripción de tu multa. Pero la notificación debe cumplir requisitos específicos.'
Update-Meta 'cobertura-seguro-carga-maritima-ecuador.html' 'Seguro de carga marítima en Ecuador: qué cubre' 'ICC A, B y C tienen diferencias importantes. Elegir la cobertura incorrecta puede dejarte sin protección para el daño que más te preocupa.'
Update-Meta 'comercio-exterior-aduanas-ecuador.html' 'Comercio exterior y aduanas en Ecuador: importaciones' 'El comercio exterior en Ecuador puede generar retenciones, multas y sanciones si no cumples los requisitos documentales.'
Update-Meta 'como-demandar-pension-alimenticia-ecuador.html' 'Cómo demandar pensión alimenticia Ecuador 2026' 'Demandar pensión alimenticia en Ecuador: tabla oficial 2026, calculadora, documentos y cómo presentar aunque el padre no haya reconocido al hijo.'
Update-Meta 'como-hacer-testamento-ecuador.html' 'Cómo hacer un testamento en Ecuador: guía 2026' 'Hacer un testamento en Ecuador requiere preparación previa con un abogado antes de ir al notario. Te explicamos el proceso completo, los documentos y.'
Update-Meta 'como-impugnar-paternidad-matrimonial-ecuador.html' 'Cómo impugnar la paternidad matrimonial Ecuador' 'Impugnar la paternidad matrimonial en Ecuador tiene un proceso diferente al del reconocimiento voluntario.'
Update-Meta 'como-limpiar-record-policial-ecuador.html' 'Cómo limpiar el récord policial en Ecuador' 'Limpiar el récord policial en Ecuador es un trámite diferente al del SATJE. Se gestiona ante la Policía Judicial y tiene requisitos específicos según.'
Update-Meta 'como-ocultar-antecedentes-fiscalia-ecuador.html' 'Cómo ocultar antecedentes en Fiscalía Ecuador' 'Puedes ocultar antecedentes en el SIAF de Fiscalía bajo la Resolución 027-FGE-2024. Te explicamos el proceso, los documentos requeridos y cómo.'
Update-Meta 'como-ocultar-nombre-satje-ecuador.html' 'Cómo ocultar tu nombre del SATJE en Ecuador' 'Ocultar tu nombre del SATJE es posible bajo la Resolución 043-2024. Si el proceso terminó y cumples los requisitos, el trámite puede iniciarse de.'
Update-Meta 'como-pedir-prueba-adn-juicio-alimentos-ecuador.html' 'Cómo pedir la prueba de ADN en juicio de alimentos' 'En un juicio de alimentos activo en Ecuador puedes solicitar la prueba de ADN. Te explicamos cómo presentar esa solicitud y qué pasa si la otra parte.'
Update-Meta 'como-presentar-oposicion-marca-ecuador.html' 'Cómo presentar una oposición de marca ante SENADI' 'Presentar una oposición de marca ante el SENADI correctamente — con los argumentos y pruebas adecuadas dentro del plazo — es lo que determina si.'
Update-Meta 'como-presentar-solicitud-prescripcion-multa-ant.html' 'Cómo redactar la solicitud de prescripción de una multa' 'Presentar la solicitud de prescripción ante la ANT requiere documentos específicos y redacción correcta.'
Update-Meta 'como-probar-engano-reconocimiento-hijo-ecuador.html' 'Cómo probar el engaño para reconocer un hijo' 'Si te engañaron para reconocer a un hijo en Ecuador, ese engaño puede ser la base de la impugnación. Te explicamos qué pruebas acepta el juez y cómo.'
Update-Meta 'como-probar-posesion-terreno-ecuador.html' 'Cómo probar la posesión de un terreno en Ecuador' 'Para ganar por prescripción necesitas probar 15 años de posesión real. Te explicamos qué documentos sirven, qué testigos acepta el juez y los errores.'
Update-Meta 'compliance-empresarial-ecuador.html' 'Compliance empresarial en Ecuador: guía práctica' 'El compliance empresarial en Ecuador protege a tu empresa de multas y a los directivos de responsabilidad personal.'
Update-Meta 'compliance-que-es-ecuador.html' 'Qué es el compliance empresarial en Ecuador' 'El compliance es el sistema que una empresa usa para cumplir sus obligaciones legales en Ecuador. Ya no es solo para grandes corporaciones.'
Update-Meta 'conciliacion-cumplida-ocultamiento-satje.html' 'Conciliación cumplida y ocultamiento en el SATJE' 'Si cumpliste una conciliación y el proceso quedó archivado, puede ocultarse del SATJE. Te explicamos los requisitos, qué documento es clave y cómo.'
Update-Meta 'concurso-meritos-antecedentes-judiciales-ecuador.html' 'Concurso de méritos con antecedentes judiciales' 'Los concursos de méritos verifican el SATJE en Ecuador. Un proceso visible aunque terminó puede generar observaciones.'
Update-Meta 'condena-cumplida-se-puede-ocultar-satje.html' 'Condena cumplida: ¿se puede ocultar del SATJE?' 'Sí, una condena cumplida puede ocultarse del SATJE en Ecuador. Requiere dos trámites: uno ante el juzgado y otro ante la Policía Judicial.'
Update-Meta 'conflictos-navieras-ecuador.html' 'Conflictos con navieras en Ecuador: cómo actuar' 'Los conflictos con navieras en Ecuador siguen patrones predecibles: demurrage mal calculado, carga dañada, cobros no acordados.'
Update-Meta 'conflictos-societarios-ecuador.html' 'Conflictos societarios en Ecuador: cómo resolverlos' 'Los conflictos societarios en Ecuador siguen patrones predecibles. Te explicamos las herramientas legales para resolver abuso de mayoría, empresas.'
Update-Meta 'conocimiento-embarque-bill-lading.html' 'Bill of Lading en Ecuador: valor legal y usos' 'El bill of lading en Ecuador no es solo un documento de transporte. Es un título de propiedad que determina quién puede retirar la carga y a quién.'
Update-Meta 'consecuencias-no-pagar-multa-transito-ecuador.html' 'Qué pasa si no pagas tus multas de tránsito' 'No pagar multas de tránsito en Ecuador genera bloqueo de matrícula, imposibilidad de renovar licencia y cobro coactivo.'
Update-Meta 'constitucion-companias-ecuador.html' 'Cómo constituir una empresa en Ecuador' 'Constituir una empresa en Ecuador correctamente desde el inicio previene conflictos costosos. Te explicamos el tipo societario correcto, el proceso.'
Update-Meta 'construcciones-arboles-prueba-posesion-ecuador.html' 'Árboles, construcciones y plantaciones como prueba d' 'Árboles, construcciones y mejoras son prueba objetiva de posesión. Un perito puede estimar su antigüedad y demostrar cuánto tiempo llevas en el.'
Update-Meta 'consultar-multas-transito-ecuador.html' 'Cómo consultar tus multas de tránsito en Ecuador' 'Consultar todas tus multas en Ecuador requiere revisar ANT, municipios y otras entidades por separado.'
Update-Meta 'contrato-confidencialidad-nda-ecuador.html' 'Acuerdo de confidencialidad NDA en Ecuador' 'Un NDA en Ecuador protege tu información confidencial frente a empleados, socios y terceros. Te explicamos cuándo usarlo, qué debe incluir y cómo.'
Update-Meta 'contrato-fletamento-ecuador.html' 'Contrato de fletamento en Ecuador: modalidades' 'El contrato de fletamento en Ecuador regula el uso del buque entre armador y fletador. Te explicamos las modalidades, las cláusulas más importantes y.'
Update-Meta 'contrato-servicios-empresa-ecuador.html' 'Contrato de servicios en Ecuador: cláusulas clave' 'Un contrato de servicios bien redactado en Ecuador protege ambas partes. Te explicamos las cláusulas esenciales y los errores más comunes que dejan.'
Update-Meta 'contrato-socios-empresa-ecuador.html' 'El pacto entre socios en Ecuador: qué debe incluir' 'El pacto entre socios previene la mayoría de los conflictos societarios en Ecuador. Te explicamos qué es, por qué es esencial y qué cláusulas debe.'
Update-Meta 'contratos-empresariales-ecuador.html' 'Contratos que toda empresa en Ecuador necesita' 'Los contratos empresariales en Ecuador protegen solo si están bien redactados. Te explicamos las cláusulas críticas y los riesgos de los contratos.'
Update-Meta 'contratos-mal-hechos-riesgos-ecuador.html' 'Riesgos de usar contratos genéricos descargados' 'Los contratos descargados de internet generan una falsa seguridad en Ecuador. Cuando hay conflicto real, las cláusulas que importan suelen fallar.'
Update-Meta 'contratos-transporte-maritimo-ecuador.html' 'Contratos de transporte marítimo en Ecuador' 'El contrato de transporte marítimo en Ecuador se formaliza principalmente en el bill of lading. Las cláusulas del reverso pueden cambiar.'
Update-Meta 'convenio-pago-multa-transito-interrumpe-prescripcion.html' 'Convenio de pago de multa: ¿interrumpe la prescripción?' 'Firmar un convenio de pago es un reconocimiento de deuda que reinicia el plazo de prescripción desde cero.'
Update-Meta 'convenios-internacionales-maritimos-ecuador.html' 'Convenios marítimos internacionales en Ecuador' 'Las Reglas de La Haya, MARPOL, SOLAS y CONVEMAR aplican en Ecuador. Te explicamos cuáles son relevantes para tu operación y qué obligaciones generan.'
Update-Meta 'copiaron-mi-marca-ecuador.html' 'Alguien usa tu marca sin permiso: qué hacer' 'Si alguien copia o usa tu marca en Ecuador sin permiso tienes acciones legales ante el SENADI. Te explicamos qué pruebas necesitas y cómo actuar.'
Update-Meta 'costo-juicio-prescripcion-adquisitiva-ecuador.html' 'Cuánto cuesta un juicio de prescripción adquisitiva' 'El costo de un juicio de prescripción adquisitiva varía según la complejidad. Te explicamos los componentes del precio y qué factores lo hacen más o.'
Update-Meta 'costo-registro-marca-senadi-ecuador.html' 'Cuánto cuesta registrar una marca en Ecuador' 'Registrar una marca en Ecuador incluye tasas del SENADI, honorarios y costos adicionales por clase. Te explicamos todos los precios reales.'
Update-Meta 'cual-prescripcion-aplica-mi-caso-ecuador.html' '¿Prescripción ordinaria o extraordinaria? Cuál aplica' 'Hay dos tipos de prescripción de multas de tránsito en Ecuador y cuál aplica depende de la fecha de la multa.'
Update-Meta 'cuando-renovar-marca-ecuador.html' 'Cuándo renovar tu marca en Ecuador: plazos' 'Renovar tu marca en Ecuador antes del vencimiento de 10 años es obligatorio. Te explicamos cuándo hacerlo, qué pasa si se vence el plazo y cómo.'
Update-Meta 'cuantas-multas-tengo-transito-ecuador.html' '¿Cuántas multas de tránsito tengo? Cómo saberlo' 'Hacer el inventario de tus multas en Ecuador requiere consultar más de un sistema. Te explicamos cómo verificar en ANT y municipios y cómo organizar.'
Update-Meta 'cuanto-cobra-abogado-impugnacion-paternidad-ecuador.html' 'Cuánto cobra un abogado por impugnación de paternidad' 'El honorario por impugnar la paternidad en Ecuador varía según la complejidad del caso. Te explicamos qué es negociable, qué no lo es y cómo calcular.'
Update-Meta 'cuanto-cuesta-crear-empresa-ecuador.html' 'Cuánto cuesta crear una empresa en Ecuador 2026' 'Crear una empresa en Ecuador tiene costos reales más allá del capital mínimo. Te explicamos escritura pública, Registro Mercantil, Supercias, RUC y.'
Update-Meta 'cuanto-cuesta-impugnar-paternidad-ecuador.html' '¿Cuánto cuesta impugnar la paternidad en Ecuador?' 'Impugnar la paternidad en Ecuador tiene costos que la mayoría no calcula: honorarios, ADN judicial, tasas y pensiones mientras dura el proceso.'
Update-Meta 'cuanto-cuesta-ocultar-antecedentes-ecuador.html' 'Cuánto cuesta ocultar los antecedentes en Ecuador' 'El costo del ocultamiento de antecedentes en Ecuador depende del número de procesos y la complejidad. Te explicamos los precios reales con todo.'
Update-Meta 'cuanto-cuesta-prueba-adn-ecuador.html' 'Prueba de ADN en Ecuador: precios 2026 y validez legal' 'Una prueba de ADN en Ecuador cuesta entre $150 y $350. Pero no toda vale en juicio. Te explicamos cuál necesitas según si el proceso es.'
Update-Meta 'cuanto-cuesta-tarda-cambio-apellido-ecuador.html' '¿Cuánto cuesta y tarda el cambio de apellido?' 'El cambio de apellido en Ecuador tiene costos y plazos distintos según la vía administrativa o judicial.'
Update-Meta 'cuanto-cuesta-testamento-ecuador.html' 'Cuánto cuesta hacer un testamento en Ecuador' 'Hacer un testamento en Ecuador cuesta entre $60 y $180 en honorarios más gastos notariales. Te explicamos qué incluye cada precio y qué conviene.'
Update-Meta 'cuanto-dura-registro-marca-ecuador.html' 'Cuánto dura el registro de marca en Ecuador' 'El registro de marca en Ecuador dura 10 años y se puede renovar indefinidamente. Te explicamos los períodos de gracia, qué pasa si vence y cómo no.'
Update-Meta 'cuanto-tarda-impugnacion-paternidad-matrimonial-ecuador.html' 'Cuánto tarda la impugnación de paternidad matrimonial' 'La impugnación de paternidad matrimonial en Ecuador es más rápida que la del reconocimiento. Te explicamos las etapas con tiempos reales y cuántas.'
Update-Meta 'cuanto-tarda-juicio-prescripcion-adquisitiva-ecuador.html' 'Cuánto tarda el juicio de prescripción adquisitiva' 'Un juicio de prescripción adquisitiva en Ecuador toma entre 1 y 3 años. Te explicamos cada etapa, cuánto dura y qué factores pueden acelerarlo o.'
Update-Meta 'cuanto-tarda-la-impugnacion-de-paternidad-reconocimiento-voluntario-ecuador.html' 'Cuánto tarda la impugnación de paternidad Ecuador' 'La impugnación por reconocimiento voluntario en Ecuador es más lenta porque exige probar más que el ADN.'
Update-Meta 'cuanto-tarda-ocultamiento-satje-ecuador.html' 'Cuánto tarda el ocultamiento en el SATJE Ecuador' 'El ocultamiento en el SATJE toma entre 2 y 8 semanas en Ecuador. Te explicamos cuánto dura cada etapa y qué factores pueden acelerarlo o retrasarlo.'
Update-Meta 'cuanto-tarda-pension-alimenticia-ecuador.html' '¿Cuánto tarda la pensión alimenticia en Ecuador?' 'La pensión provisional puede fijarse en días en Ecuador. La definitiva entre 30 y 60 días. El padre debe desde que presentas la demanda, aunque no.'
Update-Meta 'cuantos-puntos-tiene-mi-licencia-ecuador.html' '¿Cuántos puntos tiene mi licencia en Ecuador?' 'Consultar los puntos de tu licencia en el portal ANT toma menos de 5 minutos. También te explicamos cuántos se descuentan por tipo de infracción y.'
Update-Meta 'cuenta-bloqueada-coactiva-salario.html' 'Bloquearon tu cuenta por coactiva en Ecuador: qué hacer' 'Si te bloquearon la cuenta por coactiva y el dinero es tu salario, la Constitución te protege en Ecuador. El sueldo es inembargable.'
Update-Meta 'dano-economico-paternidad-falsa-ecuador.html' 'Daño económico por paternidad falsa: puedes reclamar' 'Si pagaste pensión por un hijo que no es tuyo en Ecuador puedes reclamar el daño económico. Te explicamos qué dice la ley, qué necesitas probar y qué.'
Update-Meta 'dano-mercaderia-muelle-ecuador.html' 'Daño a la mercancía en el muelle: quién paga' 'El daño a la mercancía en el muelle puede ocurrir en distintas etapas en Ecuador. El responsable varía según cuándo exactamente ocurrió.'
Update-Meta 'danos-carga-maritima-ecuador.html' 'Daños en carga marítima Ecuador: quién responde' 'La naviera responde por daños a la carga durante el transporte en Ecuador, con excepciones. Te explicamos quién asume la responsabilidad, cómo probar.'
Update-Meta 'danos-infraccion-marca-ecuador.html' 'Daños por infracción de marca en Ecuador' 'Puedes reclamar daños y perjuicios por infracción de marca en Ecuador además de detener el uso. Te explicamos qué daños son reclamables y cómo.'
Update-Meta 'demanda-judicial-interrumpe-prescripcion-ecuador.html' 'La demanda judicial interrumpe la prescripción' 'Presentar una demanda judicial es el mecanismo más efectivo para interrumpir la prescripción adquisitiva en Ecuador.'
Update-Meta 'demora-fuerza-mayor-contenedor-ecuador.html' 'Demurrage por fuerza mayor: ¿la naviera cobra?' 'La naviera puede cobrar demurrage aunque la demora no sea tu culpa en Ecuador. Te explicamos cuándo la fuerza mayor es un argumento válido y cómo.'
Update-Meta 'demoras-contenedores-puerto-ecuador.html' 'Sobreestadías en el puerto Ecuador: qué hacer' 'Las sobreestadías en puertos ecuatorianos se acumulan rápido. Te explicamos cuándo los cobros pueden cuestionarse, cómo calcular el monto correcto y.'
Update-Meta 'demurrage-demoras-contenedores-ecuador.html' 'Demurrage en Ecuador: cómo impugnar cobros' 'El demurrage en Ecuador es el cargo por no devolver el contenedor a tiempo. Muchas facturas tienen errores que puedes impugnar.'
Update-Meta 'demurrage-por-culpa-senae-aduana-ecuador.html' 'Demurrage por culpa de la SENAE: cómo reclamar' 'Cuando el canal rojo del SENAE genera demurrage en Ecuador, esos días pueden recuperarse si tienes la documentación correcta del proceso de aforo.'
Update-Meta 'derecho-corporativo-empresas-ecuador.html' 'Derecho corporativo en Ecuador: protege tu empresa' 'El derecho corporativo en Ecuador protege tu empresa frente a socios, reguladores y terceros. Te explicamos las herramientas disponibles para.'
Update-Meta 'derecho-maritimo-ecuador.html' 'Derecho marítimo en Ecuador: guía completa' 'El derecho marítimo en Ecuador regula transporte, pesca y contaminación del mar con normas nacionales e internacionales.'
Update-Meta 'derrame-hidrocarburos-mar-ecuador.html' 'Derrame de hidrocarburos en el mar Ecuador' 'Un derrame de hidrocarburos en aguas ecuatorianas activa responsabilidad civil objetiva del armador y posibles consecuencias penales.'
Update-Meta 'desalojo-terreno-ecuador.html' 'Desalojo de terreno en Ecuador: cuándo y cómo' 'El desalojo no siempre es la acción correcta para recuperar un terreno. Te explicamos cuándo procede, cuándo no y cómo elegir la herramienta legal.'
Update-Meta 'despido-intempestivo-abandono-trabajo-ecuador.html' 'Despido disfrazado de abandono: sin visto bueno es nulo' 'Si tu empleador alega abandono sin tramitar el visto bueno ante el Ministerio de Trabajo, eso es despido intempestivo.'
Update-Meta 'despido-intempestivo-discapacidad-familiar-ecuador.html' 'Despido con familiar discapacitado: 18 meses más' 'Si te despidieron con un familiar con discapacidad a cargo, tu empleador debe 18 meses adicionales en Ecuador.'
Update-Meta 'despido-intempestivo-ecuador.html' 'Despido intempestivo Ecuador: qué te deben' 'Por despido intempestivo en Ecuador te corresponde un mes por año trabajado más la liquidación completa. Tienes 3 años para reclamar.'
Update-Meta 'despues-del-ocultamiento-que-pasa-ecuador.html' 'Después del ocultamiento del SATJE: qué cambia' 'Después del ocultamiento tus datos dejan de aparecer en búsquedas públicas del SATJE. Te explicamos qué garantiza realmente el trámite y en qué casos.'
Update-Meta 'despues-interrumpir-prescripcion-que-pasa-ecuador.html' 'Despues de interrumpir la prescripcion que pasa en Ecua' 'Interrumpir la prescripción adquisitiva en Ecuador reinicia el plazo desde cero. Los años acumulados antes de la interrupción no cuentan para el.'
Update-Meta 'deudas-coactiva-satje-ocultamiento-ecuador.html' 'Deudas coactivas en el SATJE Ecuador: cómo ocultar' 'Los procesos coactivos terminados en el SATJE pueden ocultarse. Te explicamos cuándo califican, el error más frecuente que genera rechazos y cómo.'
Update-Meta 'diferencia-record-policial-satje-fiscalia-ecuador.html' 'Récord policial, SATJE y Fiscalía: diferencias' 'Récord policial, SATJE y SIAF de Fiscalía son tres sistemas distintos en Ecuador. Cada uno requiere un proceso diferente para limpiar tu información.'
Update-Meta 'diferencia-satje-siaf-en-cual-aparezco.html' 'SATJE vs SIAF de Fiscalía: en cuál apareces' 'El SATJE registra procesos judiciales y el SIAF registra investigaciones penales. En cuál apareces depende del tipo de proceso que tuviste.'
Update-Meta 'documentos-importacion-ecuador.html' 'Documentos para importar legalmente en Ecuador' 'Los documentos para importar en Ecuador varían según la mercancía. Un error puede generar retención del SENAE.'
Update-Meta 'documentos-necesarios-ocultamiento-satje-ecuador.html' 'Documentos para el ocultamiento en el SATJE Ecuador' 'Los documentos para el ocultamiento en el SATJE varían según el estado del proceso. Reunirlos correctamente antes de presentar evita demoras.'
Update-Meta 'documentos-probar-posesion-terreno-sin-escritura-ecuador.html' 'Documentos para probar posesión sin escritura' 'Si llevas años en un terreno sin escritura, hay documentos específicos que el juez acepta. Te explicamos cuáles son, cómo conseguirlos y cómo.'
Update-Meta 'donde-hacer-adn-legal-en-ecuador.html' 'Dónde hacer la prueba de ADN legal en Ecuador' 'No todos los laboratorios de ADN en Ecuador emiten resultados válidos en juicio. Te explicamos qué certificaciones buscar y la diferencia entre una.'
Update-Meta 'donde-tramitar-prescripcion-multa-transito-ecuador.html' 'Dónde tramitar la prescripción de tu multa' 'La entidad correcta para prescribir tu multa depende de la fecha y el emisor. Te explicamos la tabla de decisión y cómo presentar correctamente en.'
Update-Meta 'due-diligence-marcas-ecuador.html' 'Due diligence de marcas en Ecuador: qué revisar' 'Antes de invertir en una empresa en Ecuador verifica sus marcas. Registros vencidos, litigios o marcas sin registrar pueden ser riesgos reales.'
Update-Meta 'el-adn-negativo-no-basta-reconocimiento-voluntario-ecuador.html' 'El ADN negativo no basta si firmaste el reconocimiento' 'Si reconociste voluntariamente a un hijo en Ecuador el ADN negativo por sí solo no alcanza para impugnar. La ley exige demostrar algo más.'
Update-Meta 'el-adn-privado-sirve-en-juicio-alimentos-ecuador.html' 'El ADN privado sirve en juicio de alimentos Ecuador' 'Una prueba de ADN privada puede tener valor en juicio de alimentos en Ecuador bajo ciertas condiciones.'
Update-Meta 'el-juez-puede-ordenar-adn-juicio-alimentos-ecuador.html' 'El juez puede ordenar el ADN en juicio de alimentos' 'El juez puede ordenar el ADN de oficio en un juicio de alimentos en Ecuador aunque nadie lo pida. Te explicamos cuándo ocurre y qué pasa si la parte.'
Update-Meta 'embargo-sueldo-ecuador.html' 'Embargo de sueldo en Ecuador: qué pueden retener' 'No pueden retener tu sueldo por deudas bancarias o coactivas en Ecuador. El salario es inembargable. Te explicamos qué hacer si ya te bloquearon la.'
Update-Meta 'embargo-vehiculo-multa-transito-ecuador.html' 'Embargo por multa de tránsito: cómo oponerse' 'Con un cobro coactivo activo pueden embargar tu vehículo por multas de tránsito. Te explicamos tus derechos y cómo la prescripción puede ser la.'
Update-Meta 'empresa-revisa-satje-antes-contratar-ecuador.html' 'Las empresas revisan el SATJE antes de contratar' 'Muchas empresas en Ecuador revisan el SATJE antes de contratar. En roles sensibles esa verificación es estándar.'
Update-Meta 'endoso-bill-of-lading-ecuador.html' 'Endoso del Bill of Lading en Ecuador: riesgos' 'El endoso del bill of lading transfiere el derecho a retirar la carga en Ecuador. Un error en la cadena de endosos puede bloquear la operación.'
Update-Meta 'enriquecimiento-injusto-pensiones-paternidad-ecuador.html' 'Enriquecimiento injusto y pensiones por paternidad' 'El enriquecimiento injusto podría aplicar para recuperar pensiones pagadas por paternidad falsa en Ecuador.'
Update-Meta 'errores-crear-sas-ecuador.html' 'Errores al crear una SAS en Ecuador: cómo evitarlos' 'Los errores al crear una SAS en Ecuador ocurren antes de la inscripción: estatutos genéricos y mecanismos de gobierno vacíos.'
Update-Meta 'errores-evitar-poseyendo-sin-escritura-ecuador.html' 'Errores que destruyen tu posesión sin escritura' 'Hay actos que destruyen tu posesión aunque lleves 20 años en el terreno. Te explicamos cuáles son y cómo evitarlos para no perder el derecho a la.'
Update-Meta 'errores-frecuentes-prescripcion-multas-transito-ecuador.html' 'Errores frecuentes en la prescripción de multas' 'La mayoría de rechazos de prescripción ocurren por sede equivocada, plazo mal calculado o documentos incompletos.'
Update-Meta 'escrito-prescripcion-contravenciones-requisitos.html' 'Escrito de prescripción ante el Juez de Contravenciones' 'El escrito de prescripción ante el Juez de Contravenciones debe cumplir requisitos formales específicos.'
Update-Meta 'escrito-prescripcion-juez-contravenciones-transito.html' 'Qué incluir en el escrito de prescripción de multa' 'La prescripción judicial de multas requiere un escrito formal diferente a la solicitud administrativa.'
Update-Meta 'etapas-juicio-prescripcion-adquisitiva-ecuador.html' 'Etapas del juicio de prescripción adquisitiva' 'El juicio de prescripción adquisitiva tiene etapas definidas desde la demanda hasta el Registro de la Propiedad.'
Update-Meta 'exportar-camaron-legal-ecuador.html' 'Exportar camarón desde Ecuador: requisitos' 'Exportar camarón desde Ecuador cumpliendo todos los requisitos legales y sanitarios es la diferencia entre una operación exitosa y un embarque.'
Update-Meta 'expulsar-socio-compania-ecuador.html' '¿Se puede sacar a un socio de una empresa Ecuador?' 'Excluir a un socio de una empresa en Ecuador no es decisión unilateral. Hay causales específicas y un proceso legal.'
Update-Meta 'extincion-accion-penal-ocultamiento-ecuador.html' 'Extinción de la acción penal y ocultamiento Ecuador' 'La extinción de la acción penal cierra el proceso pero no limpia el SATJE ni el SIAF automáticamente. Te explicamos qué causales aplican y cómo.'
Update-Meta 'faltante-mercaderia-contenedor-ecuador.html' 'Faltante de mercancía en contenedor Ecuador' 'Cuando falta mercancía en un contenedor en Ecuador, cómo y cuándo documentas el faltante determina contra quién puedes reclamar.'
Update-Meta 'fideicomisos-ecuador.html' 'Fideicomisos en Ecuador: cómo funcionan y para qué' 'El fideicomiso en Ecuador protege activos personales y empresariales de forma legal. Te explicamos cómo funciona, para qué sirve y cuándo es la.'
Update-Meta 'fondos-reserva-jubilacion-patronal-ecuador.html' 'Fondos de reserva y jubilación patronal Ecuador' 'La Corte Nacional aclaró que los fondos de reserva sí cuentan para la jubilación patronal en Ecuador. Te explicamos la regla obligatoria y qué.'
Update-Meta 'fotos-facturas-servicios-prueba-posesion-ecuador.html' 'Fotos, facturas de servicios y documentos administrativ' 'Facturas de servicios, fotos con fecha y documentos administrativos son prueba válida de posesión en Ecuador.'
Update-Meta 'free-days-contenedor-negociar-naviera.html' 'Cómo negociar más free days con la naviera' 'Los free days son los días libres antes de que empiece el demurrage en Ecuador. Negociar más días al inicio puede ahorrar costos significativos en.'
Update-Meta 'ganar-oposicion-marca-ecuador.html' 'Cómo ganar una oposición de marca en Ecuador' 'Ganar una oposición de marca ante el SENADI depende de los argumentos y las pruebas desde el inicio. Te explicamos la estrategia tanto para el.'
Update-Meta 'gastos-juicio-impugnacion-paternidad-ecuador.html' 'Gastos del juicio de impugnación de paternidad' 'Antes de impugnar la paternidad en Ecuador calcula todos los gastos: ADN, tasas, honorarios y las pensiones que seguirás pagando durante el proceso.'
Update-Meta 'gastos-notariales-testamento-ecuador.html' 'Gastos notariales del testamento en Ecuador' 'Los gastos notariales del testamento en Ecuador varían según el notario y la complejidad. Te explicamos qué incluye el arancel notarial y qué.'
Update-Meta 'herederos-acciones-compania-ecuador.html' 'Qué pasa con las acciones al morir el dueño' 'Cuando el dueño de una empresa muere en Ecuador sus participaciones pasan a herederos. Si tienen conflictos entre sí, la empresa puede quedar.'
Update-Meta 'herencia-pareja-sin-matrimonio-ecuador.html' 'Herencia sin matrimonio: cómo proteger a tu pareja' 'Si no estás casado ni tienes unión de hecho reconocida en Ecuador, tu pareja no hereda nada. El testamento es la única forma de protegerla.'
Update-Meta 'herencia-sin-hijos-ni-conyugue-ecuador.html' 'Herencia sin hijos ni cónyuge: quién hereda' 'Sin hijos ni pareja en Ecuador la ley define quién hereda y puede no ser quien tú quieres. Te explicamos el orden legal y cómo cambiarlo con un.'
Update-Meta 'herencia-terreno-sin-escritura-ecuador.html' 'Heredé un terreno sin escritura: cómo regularizarlo' 'Si heredaste un terreno sin escritura puedes sumar el tiempo de posesión de tu causante al tuyo para completar los 15 años de prescripción.'
Update-Meta 'historial-infracciones-transito-ecuador.html' 'Historial de infracciones de tránsito: cómo consultar' 'Tu historial de multas está distribuido en diferentes sistemas según quién las emitió. Te explicamos cómo consultarlos todos y cómo usar esa.'
Update-Meta 'icc-a-b-c-que-cubre-ecuador.html' 'Cláusulas ICC A, B y C en Ecuador: qué cubren y cuál t' 'ICC A, B y C son los tres niveles de cobertura del seguro de carga marítima en Ecuador. La diferencia entre ellas puede ser la diferencia entre.'
Update-Meta 'impuesto-herencia-ecuador.html' 'Impuesto a la herencia en Ecuador 2026' 'El impuesto a la herencia en Ecuador lo paga cada heredero al SRI según su porción. Te explicamos cuándo aplica, cuándo está exonerado y qué tiene.'
Update-Meta 'impugnacion-acta-finiquito-contrato-colectivo-ecuador.html' 'Impugnar el finiquito en Ecuador: tienes 3 años' 'El plazo para impugnar el acta de finiquito en Ecuador es 3 años según el Código del Trabajo. Si te calcularon mal o firmaste bajo presión, todavía.'
Update-Meta 'impugnacion-juntas-generales-ecuador.html' 'Cómo impugnar decisiones de la junta de socios' 'Las decisiones de junta general de socios pueden impugnarse en Ecuador si hay vicios de procedimiento.'
Update-Meta 'impugnar-cobro-demurrage-naviera.html' 'Cómo impugnar un cobro de demurrage en Ecuador' 'Impugnar un cobro de demurrage en Ecuador es posible cuando hay errores de cálculo o días de aforo incluidos indebidamente.'
Update-Meta 'impugnar-paternidad-reconocimiento-voluntario-ecuador.html' 'Impugnar paternidad por reconocimiento voluntario' 'Impugnar la paternidad por reconocimiento voluntario en Ecuador es posible pero más exigente. Te explicamos cuándo procede, qué debes demostrar y.'
Update-Meta 'impugnar-testamento-ecuador.html' 'Impugnar un testamento en Ecuador: causales' 'Impugnar un testamento en Ecuador es posible pero las causales son específicas. Te explicamos cuándo procede, qué pruebas necesitas y cómo redactar.'
Update-Meta 'indagacion-previa-visible-fiscalia-ecuador.html' 'Mi indagación previa sigue visible en Fiscalía' 'Una indagación previa archivada puede ocultarse del SIAF de Fiscalía bajo la Resolución 027-FGE-2024. Te explicamos por qué sigue visible y cómo.'
Update-Meta 'infraccion-marca-ecuador.html' 'Infracción de marca en Ecuador: acciones legales' 'La infracción de marca en Ecuador activa tres tipos de acciones: ante el SENADI, civil y penal. Te explicamos cuál usar según el tipo y escala del.'
Update-Meta 'inspeccion-superintendencia-companias-ecuador.html' 'Inspección de la Superintendencia: cómo prepararte' 'Si tu empresa recibió una carta de inspección de la Supercias, esto es lo que revisan, los errores más frecuentes y cómo prepararte antes de la.'
Update-Meta 'interrumpir-prescripcion-adquisitiva-ecuador.html' 'Cómo interrumpir la prescripción adquisitiva' 'Puedes interrumpir el plazo de prescripción adquisitiva antes de los 15 años. Te explicamos los dos mecanismos legales disponibles en Ecuador y.'
Update-Meta 'juicio-alimentos-satje-como-ocultar.html' 'Juicio de alimentos en el SATJE Ecuador: cómo ocultar' 'Un juicio de alimentos archivado o concluido en el SATJE puede ocultarse bajo condiciones específicas.'
Update-Meta 'juicio-particion-herencia-ecuador.html' 'Juicio de partición de herencia en Ecuador' 'Si los herederos no se ponen de acuerdo cualquiera puede pedir la partición judicial en Ecuador. Te explicamos cuándo procede, cuánto tarda y qué.'
Update-Meta 'legitimas-herencia-ecuador.html' 'Legítimas en la herencia ecuatoriana: cómo funcionan' 'Las legítimas son las porciones que la ley garantiza a los herederos forzosos en Ecuador. Te explicamos cuáles son, cuánto les corresponde y qué.'
Update-Meta 'licencia-no-devuelve-puntos-prescripcion.html' 'La prescripción de multas no recupera tus puntos' 'Prescribir una multa elimina la deuda económica pero no recupera los puntos de la licencia. Son sistemas independientes.'
Update-Meta 'licencia-pesca-ecuador.html' 'Licencia de pesca en Ecuador: tipos y requisitos' 'La licencia de pesca en Ecuador es obligatoria para operar en el sector. El tipo y los requisitos varían según si la actividad es artesanal,.'
Update-Meta 'liquidacion-companias-conflictos.html' 'Cuándo conviene liquidar una empresa en conflicto' 'Cuando el conflicto entre socios en Ecuador es irresoluble, la liquidación puede ser la salida menos costosa.'
Update-Meta 'logo-slogan-registro-ecuador.html' 'Registrar logo y eslogan en Ecuador: cómo hacerlo' 'Registrar tu logo y eslogan en Ecuador te da protección específica sobre esos elementos. Te explicamos cómo hacerlo en el SENADI y qué diferencias.'
Update-Meta 'los-mensajes-de-whatsapp-sirven-como-prueba-impugnacion-ecuador.html' 'WhatsApp como prueba en impugnación de paternidad' 'Los mensajes de WhatsApp pueden ser prueba clave en impugnación de paternidad en Ecuador. Te explicamos qué tipo de mensajes sirven y cómo.'
Update-Meta 'marca-antes-de-lanzar-producto-ecuador.html' 'Registra tu marca antes de lanzar el producto' 'Lanzar sin registrar la marca en Ecuador permite que alguien más la registre primero y te bloquee legalmente.'

Write-Host "`n=== DONE === Updated=$($updated) | NoChange=$($skipped) | NotFound=$($notFound)"
